import assert from "node:assert/strict";
import test from "node:test";
import { assessCandidateAdmissibility } from "../src/candidate-admissibility.js";
import type { CapabilityQualificationResult, CapabilityQualificationStatus } from "../src/capability-qualification.js";
import type { TransactionAuthorizationResult, TransactionAuthorizationStatus } from "../src/transaction-authorization.js";

const identity={capabilityId:"web.search",providerId:"provider-a",resourceId:"resource-a"};
const qualification=(status:CapabilityQualificationStatus, patch:Partial<CapabilityQualificationResult>={}):CapabilityQualificationResult=>({status,...identity,requirementSnapshot:{requireSemanticMatch:true},dimensions:[],missingEvidence:status==="NOT_ESTABLISHED"?["SEMANTICS"]:[],failedRequirements:status==="NOT_QUALIFIED"?["SEMANTICS"]:[],...patch});
const authorization=(status:TransactionAuthorizationStatus, patch:Partial<TransactionAuthorizationResult>={}):TransactionAuthorizationResult=>({status,...identity,policySnapshot:{allowFree:true},proposalSnapshot:{...identity,invocation:{method:"GET"},payment:{status:"FREE"}},dimensions:[],missingFacts:status==="NOT_ESTABLISHED"?[{dimension:"ASSET",status:"NOT_ESTABLISHED",reasonCode:"ASSET_MISSING"}]:[],failedRequirements:status==="NOT_AUTHORIZED"?[{dimension:"PAYMENT_MODE",status:"ESTABLISHED_FAIL",reasonCode:"FREE_TRANSACTION_NOT_ALLOWED"}]:[],...patch});
const compose=(q:CapabilityQualificationStatus,a:TransactionAuthorizationStatus)=>assessCandidateAdmissibility({qualification:qualification(q),authorization:authorization(a)});

test("complete qualification/authorization truth table is exact",()=>{
 const cases:readonly [CapabilityQualificationStatus,TransactionAuthorizationStatus,"ADMISSIBLE"|"NOT_ADMISSIBLE"|"NOT_ESTABLISHED"][]=[
  ["QUALIFIED","AUTHORIZED","ADMISSIBLE"],["QUALIFIED","NOT_AUTHORIZED","NOT_ADMISSIBLE"],["QUALIFIED","NOT_ESTABLISHED","NOT_ESTABLISHED"],
  ["NOT_QUALIFIED","AUTHORIZED","NOT_ADMISSIBLE"],["NOT_QUALIFIED","NOT_AUTHORIZED","NOT_ADMISSIBLE"],["NOT_QUALIFIED","NOT_ESTABLISHED","NOT_ESTABLISHED"],
  ["NOT_ESTABLISHED","AUTHORIZED","NOT_ESTABLISHED"],["NOT_ESTABLISHED","NOT_AUTHORIZED","NOT_ESTABLISHED"],["NOT_ESTABLISHED","NOT_ESTABLISHED","NOT_ESTABLISHED"]
 ];
 for(const [q,a,expected] of cases) assert.equal(compose(q,a).status,expected,`${q} + ${a}`);
});
test("admissible has exactly coherent qualified and authorized gates",()=>{const r=compose("QUALIFIED","AUTHORIZED");assert.equal(r.status,"ADMISSIBLE");assert.deepEqual(r.missingGates,[]);assert.deepEqual(r.failedGates,[]);assert.ok(r.gates.every(x=>x.status==="ESTABLISHED_PASS"));});
test("established failures are not admissible and preserve canonical gate order",()=>{const r=compose("NOT_QUALIFIED","NOT_AUTHORIZED");assert.equal(r.status,"NOT_ADMISSIBLE");assert.deepEqual(r.failedGates,["CAPABILITY_QUALIFICATION","TRANSACTION_AUTHORIZATION"]);});
test("missing establishment globally takes precedence while retaining known failures",()=>{const a=compose("NOT_QUALIFIED","NOT_ESTABLISHED"),b=compose("NOT_ESTABLISHED","NOT_AUTHORIZED");assert.equal(a.status,"NOT_ESTABLISHED");assert.deepEqual(a.missingGates,["TRANSACTION_AUTHORIZATION"]);assert.deepEqual(a.failedGates,["CAPABILITY_QUALIFICATION"]);assert.equal(b.status,"NOT_ESTABLISHED");assert.deepEqual(b.missingGates,["CAPABILITY_QUALIFICATION"]);assert.deepEqual(b.failedGates,["TRANSACTION_AUTHORIZATION"]);});
test("both upstream unknown gates remain visible",()=>{const r=compose("NOT_ESTABLISHED","NOT_ESTABLISHED");assert.deepEqual(r.missingGates,["CAPABILITY_QUALIFICATION","TRANSACTION_AUTHORIZATION"]);});
test("candidate capability provider and explicit resource conflicts refuse establishment",()=>{for(const patch of [{capabilityId:"other"},{providerId:"provider-b"},{resourceId:"resource-b"}]){const r=assessCandidateAdmissibility({qualification:qualification("QUALIFIED"),authorization:authorization("AUTHORIZED",patch)});assert.equal(r.status,"NOT_ESTABLISHED");assert.equal(r.gates[0].reasonCode,"INCONSISTENT_CANDIDATE_IDENTITY");assert.deepEqual(r.missingGates,["IDENTITY"]);}});
test("partial resource identity is conservative without fabricated equality",()=>{const q=qualification("QUALIFIED");const a=authorization("AUTHORIZED");delete (a as {resourceId?:string}).resourceId;const r=assessCandidateAdmissibility({qualification:q,authorization:a});assert.equal(r.status,"ADMISSIBLE");assert.equal(r.identity.resourceId,"resource-a");assert.equal(r.gates[0].status,"ESTABLISHED_PASS");});
test("omitted and explicit empty resource identities remain distinct without fabricated comparison",()=>{const q=qualification("QUALIFIED",{resourceId:""});const a=authorization("AUTHORIZED");delete (a as {resourceId?:string}).resourceId;const r=assessCandidateAdmissibility({qualification:q,authorization:a});assert.equal(r.status,"ADMISSIBLE");assert.ok(Object.hasOwn(r.identity,"resourceId"));assert.equal(r.identity.resourceId,"");});
test("identity inconsistency takes precedence but retains established upstream failures",()=>{const r=assessCandidateAdmissibility({qualification:qualification("NOT_QUALIFIED"),authorization:authorization("NOT_AUTHORIZED",{providerId:"provider-b"})});assert.equal(r.status,"NOT_ESTABLISHED");assert.deepEqual(r.missingGates,["IDENTITY"]);assert.deepEqual(r.failedGates,["CAPABILITY_QUALIFICATION","TRANSACTION_AUTHORIZATION"]);});
test("upstream missing and failure details remain in detached provenance",()=>{const r=compose("NOT_QUALIFIED","NOT_ESTABLISHED");assert.deepEqual(r.provenance.qualification.failedRequirements,["SEMANTICS"]);assert.equal(r.provenance.authorization.missingFacts[0]?.dimension,"ASSET");});
test("result snapshots detach from caller-owned upstream results and are deeply immutable",()=>{const q=qualification("NOT_QUALIFIED"),a=authorization("NOT_ESTABLISHED");const r=assessCandidateAdmissibility({qualification:q,authorization:a});(q.failedRequirements as string[])[0]="OTHER";(a.missingFacts as {dimension:string}[])[0]!.dimension="OTHER";assert.deepEqual(r.provenance.qualification.failedRequirements,["SEMANTICS"]);assert.equal(r.provenance.authorization.missingFacts[0]?.dimension,"ASSET");assert.ok(Object.isFrozen(r));assert.ok(Object.isFrozen(r.gates));assert.ok(Object.isFrozen(r.provenance));assert.ok(Object.isFrozen(r.provenance.authorization.missingFacts));assert.throws(()=>{(r.failedGates as string[]).push("IDENTITY")});assert.throws(()=>{(r.identity as {providerId:string}).providerId="other"});assert.throws(()=>{(r.gates[0] as {reasonCode:string}).reasonCode="OTHER"});assert.throws(()=>{(r.provenance.qualification.requirementSnapshot as {requireSemanticMatch:boolean}).requireSemanticMatch=false});});
test("gate and collection ordering is deterministic independent of object property order",()=>{const r=compose("NOT_QUALIFIED","NOT_ESTABLISHED");assert.deepEqual(r.gates.map(x=>x.gate),["IDENTITY","CAPABILITY_QUALIFICATION","TRANSACTION_AUTHORIZATION"]);assert.deepEqual(r.missingGates,["TRANSACTION_AUTHORIZATION"]);assert.deepEqual(r.failedGates,["CAPABILITY_QUALIFICATION"]);});
test("one qualification yields caller-transaction-specific admissibility outcomes",()=>{const q=qualification("QUALIFIED");assert.equal(assessCandidateAdmissibility({qualification:q,authorization:authorization("AUTHORIZED")}).status,"ADMISSIBLE");assert.equal(assessCandidateAdmissibility({qualification:q,authorization:authorization("NOT_AUTHORIZED")}).status,"NOT_ADMISSIBLE");});
