import assert from "node:assert/strict";
import test from "node:test";
import { qualifyCandidateSet } from "../src/candidate-qualification-set.js";
import type { CandidateQualificationInput } from "../src/capability-qualification.js";

const req={requireSemanticMatch:true,requireSchemaCompatibility:true,requireExternalCanonicalSuccess:true,requireOperationalEvidence:true,requireOperationalAcceptance:true};
const c=(providerId:string,resourceId=`r:${providerId}`,patch:Partial<CandidateQualificationInput>={}):CandidateQualificationInput=>{
 const id={capabilityId:"web.search",providerId,resourceId}; return {...id,semanticClassification:{capabilityId:"web.search",resourceId,status:"matched",confidence:1,evidence:[],missingEvidence:[],rejectionReasons:[]},schemaCompatibility:{status:"compatible",inputMappings:[],outputMappings:[],transformations:[],evidence:[],missingRequirements:[],incompatibilities:[]},capabilityEvidenceState:{...id,facts:{externalCanonicalSuccessObserved:true,externalCanonicalIncompatibleObserved:false},provenance:{observedCount:1,observedAt:[]}} as any,operationalEvidenceAssessment:{status:"sufficient",evidenceReference:id} as any,operationalAcceptanceAssessment:{status:"ACCEPTED",evidenceReference:id} as any,...patch};
};
const ref=(p:string,r=`r:${p}`)=>({capabilityId:"web.search",providerId:p,resourceId:r});
const population=()=>[c("A"),c("B"),c("C","r:C",{operationalAcceptanceAssessment:{status:"REJECTED",evidenceReference:ref("C")} as any}),c("D","r:D",{schemaCompatibility:{status:"incompatible",inputMappings:[],outputMappings:[],transformations:[],evidence:[],missingRequirements:[],incompatibilities:[]}}),c("E","r:E",{operationalEvidenceAssessment:{status:"insufficient",evidenceReference:ref("E")} as any,operationalAcceptanceAssessment:{status:"NOT_EVALUATED",evidenceReference:ref("E")} as any}),c("F","r:F",{capabilityEvidenceState:{...ref("F"),facts:{externalCanonicalSuccessObserved:false,externalCanonicalIncompatibleObserved:false},provenance:{observedCount:0,observedAt:[]}} as any}),c("G","r:G",{semanticClassification:{...c("G").semanticClassification!,status:"rejected"},operationalEvidenceAssessment:{status:"insufficient",evidenceReference:ref("G")} as any,operationalAcceptanceAssessment:{status:"NOT_EVALUATED",evidenceReference:ref("G")} as any}),c("H","r:H",{operationalAcceptanceAssessment:{status:"NOT_EVALUATED",evidenceReference:ref("H")} as any})];
const result=()=>qualifyCandidateSet({capabilityId:"web.search",requirement:req,candidates:population()});
test("empty set is a valid deterministic result and still validates its requirement",()=>{const r=qualifyCandidateSet({capabilityId:"web.search",requirement:{requireSemanticMatch:true},candidates:[]});assert.equal(r.totalCandidates,0);assert.deepEqual(r.evidenceGaps,[]);assert.deepEqual(r.establishedFailures,[]);assert.throws(()=>qualifyCandidateSet({capabilityId:"web.search",requirement:{},candidates:[]}),/NO_QUALIFICATION_REQUIREMENTS/);});
test("full population partitions every candidate exactly once",()=>{const r=result();assert.deepEqual(r.counts,{qualified:2,notQualified:2,notEstablished:4});assert.equal(r.qualified.length+r.notQualified.length+r.notEstablished.length,r.totalCandidates);assert.deepEqual(r.qualified.map(x=>x.providerId),["A","B"]);assert.deepEqual(r.notQualified.map(x=>x.providerId),["C","D"]);assert.deepEqual(r.notEstablished.map(x=>x.providerId),["E","F","G","H"]);});
test("gaps and failures are descriptive, canonical, and retain failure plus missing",()=>{const r=result();const gap=(d:string,reason:string)=>r.evidenceGaps.find(x=>x.dimension===d&&x.reasonCode===reason)!;assert.deepEqual(gap("OPERATIONAL_EVIDENCE","OPERATIONAL_EVIDENCE_INSUFFICIENT").candidateKeys.map(x=>x.providerId),["E","G"]);assert.deepEqual(gap("EXTERNAL_CANONICAL_SUCCESS","EXTERNAL_CANONICAL_SUCCESS_MISSING").candidateKeys.map(x=>x.providerId),["F"]);assert.deepEqual(gap("OPERATIONAL_ACCEPTANCE","OPERATIONAL_ACCEPTANCE_NOT_EVALUATED").candidateKeys.map(x=>x.providerId),["E","G","H"]);assert.deepEqual(r.establishedFailures.map(x=>[x.dimension,x.reasonCode,x.candidateKeys.map(k=>k.providerId)]),[["SEMANTICS","SEMANTIC_MATCH_REJECTED",["G"]],["SCHEMA","SCHEMA_INCOMPATIBLE",["D"]],["OPERATIONAL_ACCEPTANCE","OPERATIONAL_ACCEPTANCE_REJECTED",["C"]]]);});
test("duplicates, capability mismatch, and invalid candidates reject atomically",()=>{const one=c("A");assert.throws(()=>qualifyCandidateSet({capabilityId:"web.search",requirement:{requireSemanticMatch:true},candidates:[one,one]}),/DUPLICATE/);assert.throws(()=>qualifyCandidateSet({capabilityId:"web.search",requirement:{requireSemanticMatch:true},candidates:[{...one,capabilityId:"unit_conversion"}]}),/MISMATCH/);assert.throws(()=>qualifyCandidateSet({capabilityId:"web.search",requirement:{requireSemanticMatch:true},candidates:[one,{...one,providerId:""}]}),/providerId/);});
test("same provider different explicit resources are independent and evidence is not pooled",()=>{const a=c("P","x",{operationalEvidenceAssessment:{status:"insufficient",evidenceReference:ref("P","x")} as any});const b=c("P","y",{operationalEvidenceAssessment:{status:"insufficient",evidenceReference:ref("P","y")} as any});const r=qualifyCandidateSet({capabilityId:"web.search",requirement:{requireOperationalEvidence:true},candidates:[a,b]});assert.equal(r.notEstablished.length,2);assert.deepEqual(r.notEstablished.map(x=>x.resourceId),["x","y"]);});
test("omitted and explicit resource identities remain distinct in canonical order",()=>{const noResource={...c("P"),resourceId:undefined,semanticClassification:{...c("P").semanticClassification!,resourceId:undefined} as any,capabilityEvidenceState:{...c("P").capabilityEvidenceState!,resourceId:undefined} as any,operationalEvidenceAssessment:{status:"sufficient",evidenceReference:{capabilityId:"web.search",providerId:"P"}} as any,operationalAcceptanceAssessment:{status:"ACCEPTED",evidenceReference:{capabilityId:"web.search",providerId:"P"}} as any};const explicit=c("P","");const a=qualifyCandidateSet({capabilityId:"web.search",requirement:{requireSemanticMatch:true},candidates:[explicit,noResource]});const b=qualifyCandidateSet({capabilityId:"web.search",requirement:{requireSemanticMatch:true},candidates:[noResource,explicit]});assert.equal(a.qualified.length,2);assert.deepEqual(a,b);assert.equal(a.qualified[0].resourceId,undefined);assert.equal(a.qualified[1].resourceId,"");});
test("input order is irrelevant and snapshots/results are detached and frozen",()=>{const candidates=population();const a=qualifyCandidateSet({capabilityId:"web.search",requirement:req,candidates});const b=qualifyCandidateSet({capabilityId:"web.search",requirement:{...req},candidates:[...candidates].reverse()});assert.deepEqual(a,b);(req as any).requireSemanticMatch=false;candidates.length=0;assert.equal(a.totalCandidates,8);assert.equal(a.requirementSnapshot.requireSemanticMatch,true);assert.ok(Object.isFrozen(a.qualified));assert.ok(Object.isFrozen(a.evidenceGaps));assert.ok(Object.isFrozen(a.evidenceGaps[0].candidateKeys));assert.throws(()=>{(a.qualified as any).push("bad");});});
