import assert from "node:assert/strict";
import test from "node:test";
import { qualifyCapability, type CapabilityQualificationInput, type CapabilityQualificationRequirement } from "../src/capability-qualification.js";

const identity={capabilityId:"web.search",providerId:"provider-a",resourceId:"resource-a"};
const semantic=(status:"matched"|"possible"|"rejected")=>({capabilityId:"web.search" as const,resourceId:"resource-a",status,confidence:90,evidence:[],missingEvidence:[],rejectionReasons:[]});
const schema=(status:"compatible"|"partially_compatible"|"incompatible"|"unknown")=>({status,inputMappings:[],outputMappings:[],transformations:[],evidence:[],missingRequirements:[],incompatibilities:[],...(status==="compatible"?{adapterPlan:{capabilityId:"web.search" as const,resourceId:"resource-a",input:{mappings:[],defaults:[],transformations:[]},output:{mappings:[],transformations:[]},unsupportedCanonicalFields:[],unusedNativeFields:[]}}:{})});
const state=(patch:Record<string,boolean>={})=>({...identity, facts:{externalCanonicalSuccessObserved:false,externalCanonicalIncompatibleObserved:false,...patch},provenance:{observedCount:0,observedAt:[]}} as CapabilityQualificationInput["capabilityEvidenceState"]);
const evidence=(status:"sufficient"|"insufficient")=>({status,evidenceReference:identity} as CapabilityQualificationInput["operationalEvidenceAssessment"]);
const acceptance=(status:"ACCEPTED"|"REJECTED"|"NOT_EVALUATED")=>({status,evidenceReference:identity} as CapabilityQualificationInput["operationalAcceptanceAssessment"]);
const q=(input:Partial<CapabilityQualificationInput>, requirements:CapabilityQualificationRequirement)=>qualifyCapability({...identity,...input},requirements);

test("full qualification passes in canonical dimension order",()=>{
 const r=q({semanticClassification:semantic("matched"),schemaCompatibility:schema("compatible"),capabilityEvidenceState:state({externalCanonicalSuccessObserved:true}),operationalEvidenceAssessment:evidence("sufficient"),operationalAcceptanceAssessment:acceptance("ACCEPTED")},{requireSemanticMatch:true,requireSchemaCompatibility:true,requireAdapterPlan:true,requireExternalCanonicalSuccess:true,requireOperationalEvidence:true,requireOperationalAcceptance:true});
 assert.equal(r.status,"QUALIFIED"); assert.deepEqual(r.dimensions.map(x=>x.dimension),["SEMANTICS","SCHEMA","ADAPTER","EXTERNAL_CANONICAL_SUCCESS","OPERATIONAL_EVIDENCE","OPERATIONAL_ACCEPTANCE"]); assert.ok(r.dimensions.every(x=>x.status==="ESTABLISHED_PASS"));
});
test("missing operational evidence and acceptance remains not established",()=>{const r=q({semanticClassification:semantic("matched"),schemaCompatibility:schema("compatible"),operationalEvidenceAssessment:evidence("insufficient"),operationalAcceptanceAssessment:acceptance("NOT_EVALUATED")},{requireSemanticMatch:true,requireSchemaCompatibility:true,requireOperationalEvidence:true,requireOperationalAcceptance:true});assert.equal(r.status,"NOT_ESTABLISHED");assert.deepEqual(r.missingEvidence,["OPERATIONAL_EVIDENCE","OPERATIONAL_ACCEPTANCE"]);});
test("established acceptance rejection is not qualified",()=>{const r=q({operationalEvidenceAssessment:evidence("sufficient"),operationalAcceptanceAssessment:acceptance("REJECTED")},{requireOperationalAcceptance:true});assert.equal(r.status,"NOT_QUALIFIED");assert.deepEqual(r.failedRequirements,["OPERATIONAL_ACCEPTANCE"]);});
test("missing evidence precedes a visible failure",()=>{const r=q({semanticClassification:semantic("rejected"),operationalEvidenceAssessment:evidence("insufficient")},{requireSemanticMatch:true,requireOperationalEvidence:true});assert.equal(r.status,"NOT_ESTABLISHED");assert.deepEqual(r.failedRequirements,["SEMANTICS"]);assert.deepEqual(r.missingEvidence,["OPERATIONAL_EVIDENCE"]);});
test("possible semantic and partial schema are not established",()=>{assert.equal(q({semanticClassification:semantic("possible")},{requireSemanticMatch:true}).status,"NOT_ESTABLISHED");assert.equal(q({schemaCompatibility:schema("partially_compatible")},{requireSchemaCompatibility:true}).status,"NOT_ESTABLISHED");});
test("explicit schema incompatibility fails",()=>{const r=q({schemaCompatibility:schema("incompatible")},{requireSchemaCompatibility:true});assert.equal(r.status,"NOT_QUALIFIED");assert.equal(r.dimensions[1].reasonCode,"SCHEMA_INCOMPATIBLE");});
test("adapter plan is established only when present and identity-consistent",()=>{assert.equal(q({schemaCompatibility:schema("compatible")},{requireAdapterPlan:true}).status,"QUALIFIED");assert.equal(q({},{requireAdapterPlan:true}).status,"NOT_ESTABLISHED");assert.equal(q({adapterPlan:{...schema("compatible").adapterPlan!,resourceId:"other"}},{requireAdapterPlan:true}).status,"NOT_ESTABLISHED");});
test("only external canonical success qualifies",()=>{assert.equal(q({capabilityEvidenceState:state()},{requireExternalCanonicalSuccess:true}).status,"NOT_ESTABLISHED");assert.equal(q({capabilityEvidenceState:state({externalCanonicalSuccessObserved:true})},{requireExternalCanonicalSuccess:true}).status,"QUALIFIED");assert.equal(q({capabilityEvidenceState:state({externalCanonicalIncompatibleObserved:true})},{requireExternalCanonicalSuccess:true}).status,"NOT_QUALIFIED");});
test("acceptance not evaluated is not established",()=>assert.equal(q({operationalEvidenceAssessment:evidence("sufficient"),operationalAcceptanceAssessment:acceptance("NOT_EVALUATED")},{requireOperationalAcceptance:true}).status,"NOT_ESTABLISHED"));
test("contradictory upstream acceptance is conservatively not established",()=>{const r=q({operationalEvidenceAssessment:evidence("insufficient"),operationalAcceptanceAssessment:acceptance("ACCEPTED")},{requireOperationalAcceptance:true});assert.equal(r.status,"NOT_ESTABLISHED");assert.equal(r.dimensions[5].reasonCode,"INCONSISTENT_UPSTREAM_EVIDENCE");});
test("mixed external canonical facts are conservatively not established",()=>{const r=q({capabilityEvidenceState:state({externalCanonicalSuccessObserved:true,externalCanonicalIncompatibleObserved:true})},{requireExternalCanonicalSuccess:true});assert.equal(r.status,"NOT_ESTABLISHED");assert.equal(r.dimensions[3].reasonCode,"INCONSISTENT_UPSTREAM_EVIDENCE");});
test("same facts support caller-defined policies",()=>{const input={semanticClassification:semantic("matched"),schemaCompatibility:schema("compatible"),operationalEvidenceAssessment:evidence("sufficient"),operationalAcceptanceAssessment:acceptance("NOT_EVALUATED")};assert.equal(q(input,{requireSemanticMatch:true,requireSchemaCompatibility:true}).status,"QUALIFIED");assert.equal(q(input,{requireSemanticMatch:true,requireSchemaCompatibility:true,requireOperationalAcceptance:true}).status,"NOT_ESTABLISHED");});
test("empty and invalid requirements are rejected",()=>{assert.throws(()=>q({},{}),/NO_QUALIFICATION_REQUIREMENTS/);assert.throws(()=>q({}, {requireSemanticMatch:"yes" as never}),/must be boolean/);});
test("identity mismatches never combine provider, capability, or resource evidence",()=>{for(const bad of [{...identity,providerId:"provider-b"},{...identity,capabilityId:"other"},{...identity,resourceId:"other"}]) { const r=q({operationalEvidenceAssessment:{status:"sufficient",evidenceReference:bad} as never},{requireOperationalEvidence:true});assert.equal(r.status,"NOT_ESTABLISHED");assert.equal(r.dimensions[4].reasonCode,"IDENTITY_MISMATCH"); }});
test("results are order independent",()=>{const input={semanticClassification:semantic("rejected"),operationalEvidenceAssessment:evidence("insufficient")};const a=q(input,{requireSemanticMatch:true,requireOperationalEvidence:true});const b=q(input,{requireOperationalEvidence:true,requireSemanticMatch:true});assert.deepEqual(a,b);});
test("result provenance is copied and immutable",()=>{const supplied=semantic("matched");const r=q({semanticClassification:supplied},{requireSemanticMatch:true});supplied.status="rejected";assert.equal((r.dimensions[0].evidenceReference as {status:string}).status,"matched");assert.ok(Object.isFrozen(r));assert.ok(Object.isFrozen(r.dimensions));assert.ok(Object.isFrozen(r.dimensions[0]));});
