import assert from "node:assert/strict";
import test from "node:test";
import { deriveCapabilityEvidenceState, decideEligibility } from "../src/capability-evidence-state.js";
import { evidenceFixtures } from "../src/evidence-state-fixtures.js";

function decisions(name:string){const input=evidenceFixtures[name];const state=deriveCapabilityEvidenceState(input);return Object.fromEntries((["discovery","inspection","verification","routing"] as const).map(t=>[t,decideEligibility(state,t,{readOnly:input.invocation?.readOnly})]));}
test("discovered-only is discoverable but conservatively not higher eligible",()=>{const d=decisions("discovered-only");assert.equal(d.discovery.eligible,true);assert.equal(d.inspection.eligible,false);assert.equal(d.verification.eligible,false);assert.equal(d.routing.eligible,false);assert.ok(d.routing.missingEvidence.includes("reliability"));});
test("semantic rejection remains discovered but cannot verify or route",()=>{const input={...evidenceFixtures["kadec0-like"],semantics:"rejected" as const};const state=deriveCapabilityEvidenceState(input);assert.equal(decideEligibility(state,"discovery").eligible,true);assert.equal(decideEligibility(state,"verification",{readOnly:true}).eligible,false);assert.ok(decideEligibility(state,"routing",{readOnly:true}).reasonCodes.includes("SEMANTICS_REJECTED"));});
test("incomplete invocation and request contract block verification",()=>{for(const input of [{...evidenceFixtures["kadec0-like"],invocation:{complete:false as const}},{...evidenceFixtures["kadec0-like"],requestContract:"partially_compatible" as const}]){const d=decideEligibility(deriveCapabilityEvidenceState(input),"verification",{readOnly:true});assert.equal(d.eligible,false);assert.ok(d.reasonCodes.some(r=>r==="INVOCATION_INCOMPLETE"||r==="REQUEST_CONTRACT_INCOMPLETE"));}});
test("kadec0-like fixture keeps possible semantics, incomplete output, and quote match separate",()=>{const state=deriveCapabilityEvidenceState(evidenceFixtures["kadec0-like"]);assert.equal(state.semantics,"possible");assert.equal(state.outputContract,"unknown");assert.equal(state.payment,"quote_matched");assert.equal(decisions("kadec0-like").verification.eligible,true);assert.equal(decisions("kadec0-like").routing.eligible,false);});
test("malformed payment challenge and incomplete StableEnrich request contract are preserved",()=>{const x=deriveCapabilityEvidenceState(evidenceFixtures["x402atlas-like"]);assert.equal(x.payment,"malformed");assert.ok(decideEligibility(x,"verification",{readOnly:true}).reasonCodes.includes("PAYMENT_CHALLENGE_MALFORMED"));const s=decisions("stableenrich-like");assert.equal(s.verification.eligible,false);assert.ok(s.verification.reasonCodes.includes("REQUEST_CONTRACT_INCOMPLETE"));});
test("simulated success never becomes external production evidence",()=>{const state=deriveCapabilityEvidenceState(evidenceFixtures["simulated-canonical-success"]);assert.equal(state.execution,"simulated_success");assert.equal(state.canonicalOutput,"simulated_success");const d=decideEligibility(state,"routing",{readOnly:true});assert.equal(d.eligible,false);assert.ok(d.reasonCodes.includes("ONLY_SIMULATED_EXECUTION_OBSERVED"));assert.ok(d.reasonCodes.includes("ONLY_SIMULATED_CANONICAL_SUCCESS"));assert.equal(state.outputContract,"incomplete");});
test("external success is represented but reliability intentionally prevents routing",()=>{const state=deriveCapabilityEvidenceState(evidenceFixtures["external-canonical-success"]);assert.equal(state.execution,"external_success");assert.equal(state.canonicalOutput,"external_success");const d=decideEligibility(state,"routing",{readOnly:true});assert.equal(d.eligible,false);assert.ok(d.reasonCodes.includes("RELIABILITY_UNESTABLISHED"));});
test("external execution failure is retained without inventing a canonical-output result",()=>{const success=evidenceFixtures["external-canonical-success"].observations![0];const state=deriveCapabilityEvidenceState({...evidenceFixtures["external-canonical-success"],observations:[{...success,outcome:"execution_failed",canonicalExtraction:{status:"failed",mappings:[],missingRequiredFields:[],diagnostics:[]},canonicalValidation:{status:"unknown",diagnostics:[]}}]});assert.equal(state.execution,"external_failure");assert.equal(state.canonicalOutput,"unobserved");const d=decideEligibility(state,"routing",{readOnly:true});assert.ok(d.reasonCodes.includes("EXTERNAL_EXECUTION_FAILED"));assert.ok(d.reasonCodes.includes("CANONICAL_OUTPUT_UNOBSERVED"));});
test("external failures and successes are both retained, independent of observation order",()=>{const fixture=evidenceFixtures["conflicting-external-observations"];const a=deriveCapabilityEvidenceState(fixture),b=deriveCapabilityEvidenceState({...fixture,observations:[...fixture.observations!].reverse()});assert.deepEqual(a,b);assert.equal(a.facts.externalExecutionSuccessObserved,true);assert.equal(a.facts.externalExecutionFailureObserved,true);assert.equal(a.execution,"mixed");assert.ok(decideEligibility(a,"routing",{readOnly:true}).reasonCodes.includes("EXTERNAL_OBSERVATIONS_CONFLICT"));});
test("payment and advertised-output contradictions are never rewritten",()=>{const mismatch={...evidenceFixtures["kadec0-like"],payment:{applicable:true,advertised:true,observedStatus:"payment_required" as const,comparison:{...evidenceFixtures["kadec0-like"].payment!.comparison!,amount:"mismatch" as const}}};const state=deriveCapabilityEvidenceState(mismatch);assert.equal(state.payment,"quote_mismatched");assert.ok(decideEligibility(state,"verification",{readOnly:true}).reasonCodes.includes("PAYMENT_QUOTE_MISMATCH"));const observedBad={...evidenceFixtures["external-canonical-success"],observations:[{...evidenceFixtures["external-canonical-success"].observations![0],outcome:"incompatible_response" as const,canonicalValidation:{status:"invalid" as const,diagnostics:[]}}]};const bad=deriveCapabilityEvidenceState(observedBad);assert.equal(bad.outputContract,"compatible");assert.equal(bad.canonicalOutput,"external_incompatible");});
test("observed external success does not rewrite an incomplete advertised output contract or encode payment authorization",()=>{const input={...evidenceFixtures["external-canonical-success"],outputContract:"unknown" as const,payment:{applicable:true,advertised:true}};const state=deriveCapabilityEvidenceState(input);assert.equal(state.outputContract,"unknown");assert.equal(state.canonicalOutput,"external_success");const decision=decideEligibility(state,"verification",{readOnly:true});assert.equal(decision.eligible,true);assert.equal("paymentAllowed" in decision,false);});
