import assert from "node:assert/strict";
import test from "node:test";
import { spawn } from "node:child_process";

const requirement = { scheme: "exact", network: "eip155:84532", amount: "20000", asset: "simulation:usdc-base-sepolia", payTo: "simulation:independent-fx", maxTimeoutSeconds: 60, extra: { name: "USDC", version: "2" } };
const payload = { x402Version: 2, accepted: requirement, payload: { simulation: { simulation: true, authorization: "SIMULATED_AUTHORIZATION:20000" } }, extensions: {} };
async function withFacilitator(run: (url: string) => Promise<void>) { const port = 33000 + Math.floor(Math.random() * 1000); const child = spawn(process.execPath, ["--import", "tsx", "facilitator-demo/src/server.ts"], { cwd: process.cwd(), env: { ...process.env, PORT: String(port) }, stdio: "ignore" }); try { for (let i = 0; i < 30; i++) { try { await fetch(`http://127.0.0.1:${port}/supported`); break; } catch { await new Promise((resolve) => setTimeout(resolve, 20)); } } await run(`http://127.0.0.1:${port}`); } finally { child.kill(); } }
async function post(url: string, path: string, value: unknown) { return fetch(`${url}${path}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(value) }); }
test("facilitator exposes V2 support and read-only verification", async () => { await withFacilitator(async (url) => { const supported = await (await fetch(`${url}/supported`)).json(); assert.deepEqual(supported, { kinds: [{ x402Version: 2, scheme: "exact", network: "eip155:84532" }], extensions: [], signers: {} }); const valid = await (await post(url, "/verify", { x402Version: 2, paymentPayload: payload, paymentRequirements: requirement })).json(); assert.deepEqual(valid, { isValid: true, extensions: { simulation: true } }); assert.deepEqual(await (await fetch(`${url}/events`)).json(), { events: ["VERIFY"] }); }); });
test("facilitator rejects tampered verification and settles only valid payloads", async () => { await withFacilitator(async (url) => { const rejected = await (await post(url, "/verify", { x402Version: 2, paymentPayload: { ...payload, accepted: { ...requirement, amount: "1" } }, paymentRequirements: requirement })).json(); assert.equal(rejected.isValid, false); const settlement = await (await post(url, "/settle", { x402Version: 2, paymentPayload: payload, paymentRequirements: requirement })).json(); assert.deepEqual(settlement, { success: true, transaction: "", network: "eip155:84532", amount: "20000", extensions: { simulation: true } }); assert.deepEqual(await (await fetch(`${url}/events`)).json(), { events: ["VERIFY_REJECTED", "SETTLE"] }); }); });
