import assert from "node:assert/strict";
import test from "node:test";
import { describeObservedShape, observeSimulatedWebSearch, type SimulatedExecutionFixture } from "../src/observed-capability.js";
import { analyzeWebSearchSchema } from "../src/schema-compatibility.js";

function fixture(overrides: Partial<SimulatedExecutionFixture> = {}): SimulatedExecutionFixture {
  return { providerId:"provider-a", resourceId:"simulated://a", observedAt:"2026-09-17T00:00:00.000Z", canonicalInput:{query:"OpenAI"}, nativeInput:{q:"OpenAI"}, httpStatus:200, contentType:"application/json", body:{results:[{url:"https://example.test",title:"Example",snippet:"text"}]}, semanticStatus:"possible", ...overrides };
}
test("direct canonical response is canonical success",()=>{const r=observeSimulatedWebSearch(fixture({nativeInput:{query:"OpenAI"}}));assert.equal(r.outcome,"canonical_success");assert.equal(r.canonicalExtraction.mappings[0].observedPath,"results[].url");assert.equal(r.executionMode,"simulated");});
test("organic link and nested href map independently of provider name",()=>{const a=observeSimulatedWebSearch(fixture({providerId:"one",body:{organic:[{link:"https://example.test",description:"x"}]}}));const b=observeSimulatedWebSearch(fixture({providerId:"completely-different",body:{organic:[{link:"https://example.test",description:"x"}]}}));const nested=observeSimulatedWebSearch(fixture({body:{data:{items:[{href:"https://example.test"}]}}}));assert.equal(a.outcome,"canonical_success");assert.deepEqual(a.canonicalExtraction.mappings,b.canonicalExtraction.mappings);assert.equal(nested.outcome,"canonical_success");assert.equal(nested.canonicalExtraction.mappings[0].observedPath,"data.items[].href");});
test("title and snippet remain optional",()=>{for(const body of [{results:[{url:"https://example.test",snippet:"x"}]},{results:[{url:"https://example.test",title:"x"}]}])assert.equal(observeSimulatedWebSearch(fixture({body})).outcome,"canonical_success");});
test("missing URL and mixed result items are conservative non-success",()=>{for(const body of [{results:[{title:"no url"}]},{results:[{url:"https://example.test"},{title:"no url"}]}]){const r=observeSimulatedWebSearch(fixture({body}));assert.equal(r.outcome,"incompatible_response");assert.notEqual(r.canonicalValidation.status,"valid");}});
test("answer-only is incompatible and malformed JSON is malformed",()=>{assert.equal(observeSimulatedWebSearch(fixture({body:{answer:"hello"}})).outcome,"incompatible_response");assert.equal(observeSimulatedWebSearch(fixture({body:"{bad json"})).outcome,"malformed_response");});
test("empty collection supplies container-only evidence",()=>{const r=observeSimulatedWebSearch(fixture({body:{results:[]}}));assert.equal(r.outcome,"structurally_informative");assert.equal(r.canonicalExtraction.status,"partial");assert.equal(r.canonicalExtraction.mappings.length,0);assert.match(r.canonicalExtraction.diagnostics[0],/no item URL shape/);});
test("execution failures and non-JSON successful responses do not validate",()=>{assert.equal(observeSimulatedWebSearch(fixture({httpStatus:500,reportedSuccess:false})).outcome,"execution_failed");assert.equal(observeSimulatedWebSearch(fixture({contentType:"text/plain"})).outcome,"malformed_response");});
test("unsafe and invalid URL protocols are rejected without fetching",()=>{for(const url of ["javascript:alert(1)","data:text/plain,x","file:///tmp/a","not a url"]) { const r=observeSimulatedWebSearch(fixture({body:{results:[{url}]}}));assert.equal(r.outcome,"incompatible_response");assert.equal(r.canonicalValidation.status,"invalid"); }});
test("semantic rejection gates structurally valid output",()=>{const r=observeSimulatedWebSearch(fixture({semanticStatus:"rejected",body:{results:[{url:"https://x.com/a"}]}}));assert.equal(r.outcome,"incompatible_response");assert.equal(r.canonicalValidation.status,"valid");});
test("observation preserves provenance without mutating advertised schema or AdapterPlan",()=>{const input={type:"object",properties:{q:{type:"string"}},required:["q"]};const output={type:"object",properties:{organic:{type:"array",items:{type:"object",properties:{link:{type:"string"}}}}}};const advertised=analyzeWebSearchSchema("advertised-resource",input,output);const before=structuredClone({input,output,advertised});const r=observeSimulatedWebSearch(fixture());assert.equal(r.observedAt,"2026-09-17T00:00:00.000Z");assert.equal(r.providerId,"provider-a");assert.deepEqual({input,output,advertised},before);assert.equal("adapterPlan" in r,false);assert.equal("advertisedSchema" in r,false);});
test("shape traversal is bounded for deep, huge objects and arrays",()=>{let deep: unknown={};let cursor=deep as Record<string,unknown>;for(let i=0;i<30;i++){cursor.next={};cursor=cursor.next as Record<string,unknown>;}const enormous=Object.fromEntries(Array.from({length:100},(_,i)=>[`property${i}`,i]));const shape=describeObservedShape({deep,enormous,items:Array.from({length:100},()=>({url:"https://example.test"}))});assert.equal(shape.kind,"object");assert.ok(shape.properties!.find(x=>x.name==="enormous")!.shape.truncated);assert.equal(shape.properties!.find(x=>x.name==="items")!.shape.sampledItems,3);});
test("accepted native input is observation-specific",()=>{const r=observeSimulatedWebSearch(fixture({nativeInput:{q:"OpenAI"}}));assert.deepEqual(r.requestEvidence.nativeInputShape,{q:"OpenAI"});assert.equal(r.requestEvidence.accepted,true);});
