import assert from "node:assert/strict";
import test from "node:test";
import { ObservationLedger, assessEvidenceSufficiency, createObservationRecord, deriveContractFingerprint, deriveEvidenceMeasurements, deriveRequestFingerprint } from "../src/observation-ledger.js";

const base=(id:string, patch:Record<string,unknown>={})=>({observationId:id,capabilityId:"web.search",providerId:"p",resourceId:"r",observedAt:"2026-01-01T00:00:00.000Z",executionMode:"external" as const,source:"fixture" as const,transport:{attempted:true,reached:true,status:200,latencyMs:10},execution:{attempted:true,succeeded:true},canonicalOutput:{evaluated:true,succeeded:true},...patch});
test("append is immutable through input, reads, windows, and nested runtime references",()=>{const l=new ObservationLedger(), nested={inner:{value:"original"}}, input={...base("one"),provenance:nested as unknown as Record<string,string>};l.append(input);input.providerId="changed";nested.inner.value="changed";assert.equal(l.all()[0].providerId,"p");assert.equal((l.all()[0].provenance as unknown as {inner:{value:string}}).inner.value,"original");assert.throws(()=>l.append(base("one")),/duplicate/);const read=l.all()[0], window=l.select({capabilityId:"web.search",providerId:"p"});assert.throws(()=>{(read.transport as {latencyMs:number}).latencyMs=99;});assert.throws(()=>{(window.selectedObservationIds as string[]).push("mutate");});assert.throws(()=>{((window.observations[0].provenance as unknown as {inner:{value:string}}).inner as {value:string}).value="mutate";});assert.equal(l.all()[0].transport.latencyMs,10);});
test("appendMany is atomic for duplicate IDs and invalid records",()=>{const l=new ObservationLedger();assert.throws(()=>l.appendMany([base("a"),base("a")]));assert.equal(l.all().length,0);assert.throws(()=>l.appendMany([base("valid"),base("bad",{transport:{attempted:true,latencyMs:-1}})]));assert.equal(l.all().length,0);l.appendMany([base("a"),base("b")]);assert.equal(l.all().length,2);});
test("filters capability provider resource modes contracts and requests",()=>{const l=new ObservationLedger(), c=deriveContractFingerprint({v:1})!, r=deriveRequestFingerprint("web.search",{query:"secret"});l.appendMany([base("a",{contractFingerprint:c,requestFingerprint:r}),base("b",{providerId:"other"}),base("c",{executionMode:"simulated"})]);assert.deepEqual(l.select({capabilityId:"web.search",providerId:"p",resourceId:"r",contractFingerprint:c,requestFingerprint:r}).selectedObservationIds,["a"]);assert.deepEqual(l.select({capabilityId:"web.search",providerId:"p"}).selectedObservationIds,["a"]);assert.deepEqual(l.select({capabilityId:"web.search",providerId:"p",executionMode:"simulated"}).selectedObservationIds,["c"]);});
test("time boundaries are explicit and equal timestamps order by ID",()=>{const l=new ObservationLedger();l.appendMany([base("z",{observedAt:"2026-01-02T00:00:00.000Z"}),base("a",{observedAt:"2026-01-02T00:00:00.000Z"}),base("old",{observedAt:"2026-01-01T00:00:00.000Z"}),base("new",{observedAt:"2026-01-03T00:00:00.000Z"})]);const w=l.select({capabilityId:"web.search",providerId:"p",fromInclusive:"2026-01-02T00:00:00.000Z",toExclusive:"2026-01-03T00:00:00.000Z"});assert.deepEqual(w.selectedObservationIds,["a","z"]);});
test("quote-only does not become execution evidence",()=>{const l=new ObservationLedger();l.append(base("q",{transport:{attempted:true,reached:true,status:402},execution:{attempted:false},canonicalOutput:{evaluated:false},payment:{applicable:true,quoteObserved:true,quoteMatched:true}}));const m=deriveEvidenceMeasurements(l.select({capabilityId:"web.search",providerId:"p"}));assert.equal(m.quoteObservations,1);assert.equal(m.quoteMatches,1);assert.equal(m.executionAttempts,0);assert.equal(m.executionSuccessRatio,undefined);});
test("measurements ratios and transport latency are deterministic",()=>{const l=new ObservationLedger();l.appendMany([base("a",{transport:{attempted:true,reached:true,latencyMs:5}}),base("b",{execution:{attempted:true,succeeded:false},canonicalOutput:{evaluated:true,succeeded:false}})]);const m=deriveEvidenceMeasurements(l.select({capabilityId:"web.search",providerId:"p"}));assert.equal(m.executionSuccessRatio,.5);assert.equal(m.canonicalSuccessRatio,.5);assert.deepEqual(m.transportLatency,{count:2,min:5,max:10,mean:7.5});});
test("latency and evidence consistency validate",()=>{assert.throws(()=>createObservationRecord(base("x",{transport:{attempted:true,latencyMs:-1}})),/latency/);assert.throws(()=>createObservationRecord(base("x",{execution:{attempted:false,succeeded:true}})),/execution result/);});
test("mixed and unknown contracts are visible and can fail caller requirements",()=>{const l=new ObservationLedger(),a=deriveContractFingerprint({a:1})!,b=deriveContractFingerprint({a:2})!;l.appendMany([base("a",{contractFingerprint:a}),base("b",{contractFingerprint:b}),base("u")]);const w=l.select({capabilityId:"web.search",providerId:"p"});assert.equal(w.mixedContracts,true);assert.equal(w.unknownContractObservations,1);assert.equal(assessEvidenceSufficiency(w,{minimumExecutionAttempts:3,minimumCanonicalEvaluations:3,minimumLatencySamples:3,requireSingleContractFingerprint:true}).sufficient,false);assert.equal(assessEvidenceSufficiency(l.select({capabilityId:"web.search",providerId:"p",contractFingerprint:a}),{minimumExecutionAttempts:1,requireSingleContractFingerprint:true}).sufficient,true);});
test("measurements and windows do not depend on append order",()=>{const records=[base("b",{execution:{attempted:true,succeeded:false}}),base("a")], one=new ObservationLedger(),two=new ObservationLedger();one.appendMany(records);two.appendMany([...records].reverse());const first=one.select({capabilityId:"web.search",providerId:"p"}), second=two.select({capabilityId:"web.search",providerId:"p"});assert.deepEqual(first.selectedObservationIds,second.selectedObservationIds);assert.deepEqual(first.contractFingerprints,second.contractFingerprints);assert.deepEqual(deriveEvidenceMeasurements(first),deriveEvidenceMeasurements(second));assert.deepEqual(assessEvidenceSufficiency(first,{minimumExecutionAttempts:3}),assessEvidenceSufficiency(second,{minimumExecutionAttempts:3}));});
test("fingerprints are deterministic, key-order independent, and private",()=>{const a=deriveContractFingerprint({b:2,a:{z:1}}),b=deriveContractFingerprint({a:{z:1},b:2}), query="private customer search 12345",f=deriveRequestFingerprint("web.search",{query,limit:5});assert.equal(a,b);assert.equal(f.includes(query),false);assert.equal(f,deriveRequestFingerprint("web.search",{limit:9,query:"other"}));});
