import assert from "node:assert/strict";
import test from "node:test";
import { deriveContractFingerprint, deriveEvidenceMeasurements, ObservationLedger } from "../src/observation-ledger.js";
import { assessOperationalEvidence, type OperationalEvidenceRequirement } from "../src/operational-evidence.js";

const AS_OF = "2026-09-17T12:00:00.000Z";
const base = (id: string, patch: Record<string, unknown> = {}) => ({ observationId:id, capabilityId:"cap", providerId:"provider", observedAt:"2026-09-17T11:00:00.000Z", executionMode:"external" as const, source:"fixture" as const, contractFingerprint:"contract-v1", transport:{attempted:true,reached:true,latencyMs:10}, execution:{attempted:true,succeeded:true}, canonicalOutput:{evaluated:true,succeeded:true}, ...patch });
const assess = (records: readonly Record<string, unknown>[], req: Omit<OperationalEvidenceRequirement,"asOf"> = {}) => { const l=new ObservationLedger(); l.appendMany(records as never); const w=l.select({capabilityId:"cap",providerId:"provider",executionMode:(records[0]?.executionMode as "external"|"simulated"|undefined)}); return assessOperationalEvidence(w,deriveEvidenceMeasurements(w),{asOf:AS_OF,...req}); };

test("valid external evidence carries literal measurements and temporal provenance",()=>{const a=assess([base("a")],{minimumExecutionAttempts:1,minimumExecutionSuccesses:1,minimumCanonicalEvaluations:1,minimumCanonicalSuccesses:1,minimumTransportLatencySamples:1,requireSingleKnownContractFingerprint:true});assert.equal(a.status,"sufficient");assert.equal(a.evidenceSummary.executionSuccessRatio,1);assert.equal(a.evidenceSummary.newestObservationAgeMs,3_600_000);assert.equal(a.evidenceSummary.evidenceSpanMs,0);});
test("malformed or unsafe requirements reject without normalization",()=>{const l=new ObservationLedger(),w=l.select({capabilityId:"cap",providerId:"provider"}),m=deriveEvidenceMeasurements(w);for(const requirement of [{asOf:"no"},{asOf:AS_OF,minimumExecutionAttempts:-1},{asOf:AS_OF,minimumExecutionAttempts:1.5},{asOf:AS_OF,minimumExecutionAttempts:Number.NaN},{asOf:AS_OF,maximumNewestObservationAgeMs:Infinity},{asOf:AS_OF,maximumOldestObservationAgeMs:-1},{asOf:AS_OF,minimumEvidenceSpanMs:-1},{asOf:AS_OF,minimumExecutionAttempts:2_147_483_648}]) assert.throws(()=>assessOperationalEvidence(w,m,requirement as OperationalEvidenceRequirement));});
test("empty evidence has no temporal derived values",()=>{const a=assess([]);assert.equal(a.status,"insufficient");assert.deepEqual(a.reasonCodes,["NO_OBSERVATIONS"]);assert.equal(a.evidenceSummary.latestObservedAt,undefined);assert.equal(a.evidenceSummary.newestObservationAgeMs,undefined);});
test("all count minima and evidence-presence flags are independently assessed",()=>{const failed=base("f",{execution:{attempted:true,succeeded:false},canonicalOutput:{evaluated:true,succeeded:false},transport:{attempted:true}});const a=assess([failed],{minimumExecutionAttempts:2,minimumExecutionSuccesses:1,minimumCanonicalEvaluations:2,minimumCanonicalSuccesses:1,minimumTransportLatencySamples:1,requireExecutionSuccessEvidence:true,requireCanonicalSuccessEvidence:true});assert.deepEqual(a.reasonCodes,["INSUFFICIENT_EXECUTION_ATTEMPTS","INSUFFICIENT_EXECUTION_SUCCESSES","INSUFFICIENT_CANONICAL_EVALUATIONS","INSUFFICIENT_CANONICAL_SUCCESSES","INSUFFICIENT_LATENCY_SAMPLES","EXECUTION_SUCCESS_EVIDENCE_MISSING","CANONICAL_SUCCESS_EVIDENCE_MISSING"]);assert.deepEqual(a.missingEvidence.map(x=>x.kind),["execution_attempts","execution_successes","canonical_evaluations","canonical_successes","transport_latency_samples","execution_success_evidence","canonical_success_evidence"]);});
test("newest and oldest age are distinct, span is caller-defined, and equality passes",()=>{const rows=[base("old",{observedAt:"2026-09-16T10:00:00.000Z"}),base("new",{observedAt:"2026-09-17T11:00:00.000Z"})];const a=assess(rows,{maximumNewestObservationAgeMs:3_700_000,maximumOldestObservationAgeMs:10_000_000,minimumEvidenceSpanMs:100_000_000});assert.deepEqual(a.reasonCodes,["OLDEST_OBSERVATION_TOO_OLD","EVIDENCE_SPAN_TOO_SHORT"]);assert.equal(a.evidenceSummary.oldestObservationAgeMs,93_600_000);assert.equal(assess(rows,{maximumNewestObservationAgeMs:3_600_000,maximumOldestObservationAgeMs:93_600_000,minimumEvidenceSpanMs:90_000_000}).status,"sufficient");});
test("future-dated evidence is conservative and never yields negative ages",()=>{const a=assess([base("future",{observedAt:"2026-09-17T13:00:00.000Z"})],{maximumNewestObservationAgeMs:1});assert.deepEqual(a.reasonCodes,["FUTURE_DATED_OBSERVATION"]);assert.equal(a.evidenceSummary.newestObservationAgeMs,undefined);});
test("single known contract rejects mixed, unknown, and absent known fingerprints",()=>{const c2=deriveContractFingerprint({v:2})!;assert.deepEqual(assess([base("a"),base("b",{contractFingerprint:c2}),base("u",{contractFingerprint:undefined})],{requireSingleKnownContractFingerprint:true}).reasonCodes,["MIXED_CONTRACTS","UNKNOWN_CONTRACT_EVIDENCE"]);assert.deepEqual(assess([base("u",{contractFingerprint:undefined})],{requireSingleKnownContractFingerprint:true}).reasonCodes,["UNKNOWN_CONTRACT_EVIDENCE","NO_KNOWN_CONTRACT"]);assert.equal(assess([base("a")],{requireSingleKnownContractFingerprint:true}).status,"sufficient");});
test("same observed ratio does not make the small sample sufficient",()=>{const make=(n:number)=>Array.from({length:n},(_,i)=>base(`r${i}`,{execution:{attempted:true,succeeded:i%4!==3},canonicalOutput:{evaluated:true,succeeded:i%4!==3}}));const small=assess(make(4),{minimumExecutionAttempts:20}),large=assess(make(100),{minimumExecutionAttempts:20});assert.equal(small.evidenceSummary.executionSuccessRatio,.75);assert.equal(large.evidenceSummary.executionSuccessRatio,.75);assert.equal(small.status,"insufficient");assert.equal(large.status,"sufficient");});
test("quote-only records cannot meet execution needs and simulated records cannot meet external mode",()=>{const quotes=Array.from({length:100},(_,i)=>base(`q${i}`,{execution:{attempted:false},canonicalOutput:{evaluated:false},payment:{applicable:true,quoteObserved:true,quoteMatched:true}}));const quoteAssessment=assess(quotes,{minimumExecutionAttempts:1,requireExecutionSuccessEvidence:true,requireCanonicalSuccessEvidence:true});assert.deepEqual([quoteAssessment.evidenceSummary.executionAttempts,quoteAssessment.evidenceSummary.executionSuccesses,quoteAssessment.evidenceSummary.canonicalEvaluations,quoteAssessment.evidenceSummary.canonicalSuccesses],[0,0,0,0]);assert.deepEqual(quoteAssessment.reasonCodes,["INSUFFICIENT_EXECUTION_ATTEMPTS","EXECUTION_SUCCESS_EVIDENCE_MISSING","CANONICAL_SUCCESS_EVIDENCE_MISSING"]);const sim=base("s",{executionMode:"simulated"});assert.deepEqual(assess([sim],{requireExternalMode:true}).reasonCodes,["EXTERNAL_MODE_REQUIRED"]);});
test("assessment and missing-evidence ordering do not depend on ledger append order",()=>{const rows=[base("b",{observedAt:"2026-09-16T00:00:00.000Z",execution:{attempted:true,succeeded:false}}),base("a")], req={minimumExecutionAttempts:3,maximumNewestObservationAgeMs:1};const left=assess(rows,req),right=assess([...rows].reverse(),req);assert.deepEqual(left,right);});
