import assert from "node:assert/strict";
import test from "node:test";
import { ObservationLedger, deriveEvidenceMeasurements } from "../src/observation-ledger.js";
import { assessOperationalEvidence, type OperationalEvidenceRequirement } from "../src/operational-evidence.js";
import { assessOperationalAcceptance, type OperationalAcceptanceCriteria } from "../src/operational-acceptance.js";

const AS_OF="2026-09-17T12:00:00.000Z";
const row=(id:string, patch:Record<string,unknown>={})=>({observationId:id,capabilityId:"cap",providerId:"provider",observedAt:"2026-09-17T11:00:00.000Z",executionMode:"external" as const,source:"fixture" as const,contractFingerprint:"v1",transport:{attempted:true,reached:true,latencyMs:800},execution:{attempted:true,succeeded:true},canonicalOutput:{evaluated:true,succeeded:true},...patch});
const evidence=(rows:Record<string,unknown>[], requirement:Omit<OperationalEvidenceRequirement,"asOf">={})=>{const ledger=new ObservationLedger();ledger.appendMany(rows as never);const window=ledger.select({capabilityId:"cap",providerId:"provider"});return assessOperationalEvidence(window,deriveEvidenceMeasurements(window),{asOf:AS_OF,...requirement});};
const accept=(rows:Record<string,unknown>[], requirements:Omit<OperationalEvidenceRequirement,"asOf">, criteria:OperationalAcceptanceCriteria)=>assessOperationalAcceptance({evidenceAssessment:evidence(rows,requirements),criteria});
const samples=(n:number, patch:(i:number)=>Record<string,unknown>=()=>({}))=>Array.from({length:n},(_,i)=>row(`r${i}`,patch(i)));

test("same sufficient evidence supports caller-specific accepted and rejected interpretations",()=>{const rows=samples(100,i=>({execution:{attempted:true,succeeded:i<97},canonicalOutput:{evaluated:true,succeeded:i<99}}));const a=accept(rows,{minimumExecutionAttempts:20,minimumCanonicalEvaluations:20,minimumTransportLatencySamples:1},{minimumExecutionSuccessRatio:.95,minimumCanonicalSuccessRatio:.98,maximumMeanTransportLatencyMs:1000});const b=accept(rows,{minimumExecutionAttempts:20,minimumCanonicalEvaluations:20,minimumTransportLatencySamples:1},{minimumExecutionSuccessRatio:.99,minimumCanonicalSuccessRatio:.995,maximumMeanTransportLatencyMs:500});assert.equal(a.status,"ACCEPTED");assert.equal(b.status,"REJECTED");assert.deepEqual(b.reasonCodes,["EXECUTION_SUCCESS_RATIO_BELOW_MINIMUM","CANONICAL_SUCCESS_RATIO_BELOW_MINIMUM","MEAN_TRANSPORT_LATENCY_ABOVE_MAXIMUM"]);});
test("insufficient evidence gates acceptance without performance comparisons",()=>{const rows=samples(4,i=>({execution:{attempted:true,succeeded:i<3}}));const a=accept(rows,{minimumExecutionAttempts:20},{minimumExecutionSuccessRatio:.70});assert.equal(a.status,"NOT_EVALUATED");assert.deepEqual(a.reasonCodes,["EVIDENCE_INSUFFICIENT"]);assert.deepEqual(a.criterionResults,[]);});
test("all passing criteria accept, equality passes, and provenance is retained immutably",()=>{const a=accept(samples(20),{minimumExecutionAttempts:20,minimumCanonicalEvaluations:20,minimumTransportLatencySamples:20},{minimumExecutionSuccessRatio:1,minimumCanonicalSuccessRatio:1,maximumMeanTransportLatencyMs:800,maximumMaxTransportLatencyMs:800});assert.equal(a.status,"ACCEPTED");assert.ok(a.criterionResults.every(x=>x.status==="passed"));assert.equal(a.evidenceReference.capabilityId,"cap");assert.equal(a.evidenceReference.selectedObservationIds.length,20);assert.ok(Object.isFrozen(a.evidenceReference));assert.ok(Object.isFrozen(a.evidenceReference.evidenceWindow));assert.ok(Object.isFrozen(a.evidenceReference.selectedObservationIds));});
test("a single failure rejects and all failures remain visible in canonical order",()=>{const rows=samples(20,i=>({execution:{attempted:true,succeeded:i<19},canonicalOutput:{evaluated:true,succeeded:i<18},transport:{attempted:true,latencyMs:2000}}));const a=accept(rows,{minimumExecutionAttempts:20},{minimumExecutionSuccessRatio:1,minimumCanonicalSuccessRatio:1,maximumMeanTransportLatencyMs:1000,maximumMaxTransportLatencyMs:1000});assert.equal(a.status,"REJECTED");assert.deepEqual(a.reasonCodes,["EXECUTION_SUCCESS_RATIO_BELOW_MINIMUM","CANONICAL_SUCCESS_RATIO_BELOW_MINIMUM","MEAN_TRANSPORT_LATENCY_ABOVE_MAXIMUM","MAX_TRANSPORT_LATENCY_ABOVE_MAXIMUM"]);});
test("requested absent measurements are unavailable, never fabricated as zero",()=>{const executionOnly=samples(20,()=>({canonicalOutput:{evaluated:false},transport:{attempted:true}}));const e=accept(executionOnly,{minimumExecutionAttempts:20},{minimumExecutionSuccessRatio:.9,minimumCanonicalSuccessRatio:.9,maximumMeanTransportLatencyMs:10});assert.equal(e.status,"NOT_EVALUATED");assert.deepEqual(e.reasonCodes,["CANONICAL_SUCCESS_RATIO_UNAVAILABLE","TRANSPORT_LATENCY_UNAVAILABLE"]);assert.equal(e.criterionResults[0].status,"passed");const noExecution=samples(1,()=>({execution:{attempted:false},canonicalOutput:{evaluated:false}}));const x=accept(noExecution,{}, {minimumExecutionSuccessRatio:.9});assert.equal(x.status,"NOT_EVALUATED");assert.deepEqual(x.reasonCodes,["EXECUTION_SUCCESS_RATIO_UNAVAILABLE"]);});
test("empty criteria are not operational approval",()=>{const a=accept(samples(1),{},{});assert.equal(a.status,"NOT_EVALUATED");assert.deepEqual(a.reasonCodes,["NO_ACCEPTANCE_CRITERIA"]);});
test("criteria validation rejects malformed thresholds without partial evaluation",()=>{const sufficient=evidence(samples(1),{});for(const criteria of [{minimumExecutionSuccessRatio:-.1},{minimumExecutionSuccessRatio:1.1},{minimumExecutionSuccessRatio:NaN},{minimumCanonicalSuccessRatio:Infinity},{maximumMeanTransportLatencyMs:-1},{maximumMaxTransportLatencyMs:NaN},{maximumMeanTransportLatencyMs:Infinity}]) assert.throws(()=>assessOperationalAcceptance({evidenceAssessment:sufficient,criteria}));});
test("execution and canonical success, and transport mean and max, remain independent",()=>{const canonical=accept(samples(100,i=>({canonicalOutput:{evaluated:true,succeeded:i<80}})),{minimumExecutionAttempts:100,minimumCanonicalEvaluations:100},{minimumExecutionSuccessRatio:.99,minimumCanonicalSuccessRatio:.95});assert.equal(canonical.criterionResults[0].status,"passed");assert.equal(canonical.criterionResults[1].status,"failed");const latency=accept([100,100,100,2000].map((latencyMs,i)=>row(`l${i}`,{transport:{attempted:true,latencyMs}})),{minimumTransportLatencySamples:4},{maximumMeanTransportLatencyMs:600,maximumMaxTransportLatencyMs:1500});assert.deepEqual(latency.criterionResults.map(x=>x.status),["passed","failed"]);});
test("criterion output ignores criteria object insertion order",()=>{const e=evidence(samples(1),{});const a=assessOperationalAcceptance({evidenceAssessment:e,criteria:{minimumExecutionSuccessRatio:1,maximumMaxTransportLatencyMs:800,minimumCanonicalSuccessRatio:1,maximumMeanTransportLatencyMs:800}});const b=assessOperationalAcceptance({evidenceAssessment:e,criteria:{maximumMeanTransportLatencyMs:800,minimumCanonicalSuccessRatio:1,maximumMaxTransportLatencyMs:800,minimumExecutionSuccessRatio:1}});assert.deepEqual(a,b);});
