import assert from "node:assert/strict";
import test from "node:test";
import { selectPerformanceCandidate } from "../src/performance-selection.js";
import type { SelectionMeasurementComparabilityResult } from "../src/selection-measurement-comparability.js";
const cap="web.search";
function comparable(family:SelectionMeasurementComparabilityResult["measurementFamily"], rows:readonly [string,Record<string,number>][]):SelectionMeasurementComparabilityResult {return {status:"COMPARABLE",capabilityId:cap,measurementFamily:family,candidateCount:rows.length,requirements:{measurementFamily:family},dimensions:[],candidateContexts:rows.map(([providerId,measurement])=>({identity:{capabilityId:cap,providerId},measurementFamily:family,measurement,observationCount:1,executionMode:"external",asOf:"2026-01-01T00:00:00.000Z",contractState:"SINGLE_KNOWN"})),missingComparabilityFacts:[],failedComparabilityRequirements:[],reasonCodes:["COMPARABLE"],provenance:{assessment:"BASELINE_MEASUREMENT_COMPARABILITY",projectionStatuses:[]}};}
const choose=(c:SelectionMeasurementComparabilityResult,criterion:any)=>selectPerformanceCandidate({comparability:c,policy:{criterion}});
test("selects global exact canonical and execution ratio extrema",()=>{assert.equal(choose(comparable("CANONICAL_SUCCESS",[["a",{numerator:98,denominator:100,ratio:.98}],["b",{numerator:99,denominator:100,ratio:.99}],["c",{numerator:95,denominator:100,ratio:.95}]]),"HIGHEST_CANONICAL_SUCCESS_RATIO").selected!.identity.providerId,"b");assert.equal(choose(comparable("EXECUTION_SUCCESS",[["a",{numerator:9,denominator:10,ratio:.9}],["b",{numerator:8,denominator:10,ratio:.8}]]),"HIGHEST_EXECUTION_SUCCESS_RATIO").selected!.identity.providerId,"a");});
test("preserves exact rational ties and ignores sample quantity",()=>{const r=choose(comparable("CANONICAL_SUCCESS",[["c",{numerator:49,denominator:50,ratio:.98}],["b",{numerator:980,denominator:1000,ratio:.98}],["a",{numerator:98,denominator:100,ratio:.98}]]),"HIGHEST_CANONICAL_SUCCESS_RATIO");assert.equal(r.selected!.identity.providerId,"a");assert.deepEqual(r.tiedPreferredCandidates.map(x=>x.identity.providerId),["a","b","c"]);});
test("BigInt cross multiplication selects near safe-integer ratios",()=>{const r=choose(comparable("CANONICAL_SUCCESS",[["a",{numerator:9007199254740989,denominator:9007199254740991,ratio:1-2/9007199254740991}],["b",{numerator:9007199254740990,denominator:9007199254740991,ratio:1-1/9007199254740991}]]),"HIGHEST_CANONICAL_SUCCESS_RATIO");assert.equal(r.selected!.identity.providerId,"b");});
test("selects latency, retains latency ties, and input order is irrelevant",()=>{const c=comparable("TRANSPORT_LATENCY",[["c",{sampleCount:2,meanMs:80}],["b",{sampleCount:1000,meanMs:50}],["a",{sampleCount:100,meanMs:50}]]);const r=choose(c,"LOWEST_MEAN_TRANSPORT_LATENCY");assert.equal(r.selected!.identity.providerId,"a");assert.deepEqual(r.tiedPreferredCandidates.map(x=>x.identity.providerId),["a","b"]);assert.deepEqual(r,choose({...c,candidateContexts:[...c.candidateContexts].reverse()},"LOWEST_MEAN_TRANSPORT_LATENCY"));});
test("refuses non-comparable, mismatch, and internally inconsistent upstream data",()=>{const c=comparable("CANONICAL_SUCCESS",[["a",{numerator:1,denominator:2,ratio:.5}],["b",{numerator:1,denominator:2,ratio:.5}]]);assert.equal(choose({...c,status:"NOT_COMPARABLE"},"HIGHEST_CANONICAL_SUCCESS_RATIO").reasonCodes[0],"COMPARABILITY_NOT_SATISFIED");assert.equal(choose(c,"LOWEST_MEAN_TRANSPORT_LATENCY").reasonCodes[0],"CRITERION_MEASUREMENT_FAMILY_MISMATCH");for(const bad of [{numerator:1,denominator:0,ratio:0},{numerator:9,denominator:10,ratio:.1}])assert.equal(choose(comparable("CANONICAL_SUCCESS",[["a",bad],["b",{numerator:1,denominator:2,ratio:.5}]]),"HIGHEST_CANONICAL_SUCCESS_RATIO").reasonCodes[0],"INCONSISTENT_COMPARABILITY_RESULT");assert.equal(choose(comparable("TRANSPORT_LATENCY",[["a",{meanMs:-1}],["b",{meanMs:2}]]),"LOWEST_MEAN_TRANSPORT_LATENCY").status,"NOT_ESTABLISHED");});
test("detaches and freezes outputs",()=>{const c=comparable("CANONICAL_SUCCESS",[["a",{numerator:1,denominator:2,ratio:.5}],["b",{numerator:2,denominator:2,ratio:1}]]),policy={criterion:"HIGHEST_CANONICAL_SUCCESS_RATIO" as const},r=selectPerformanceCandidate({comparability:c,policy});c.candidateContexts[1]!.measurement.numerator=0;assert.equal(r.selected!.measurement.numerator,2);assert.throws(()=>{(r.candidates as unknown as unknown[]).push({});});});
