import assert from "node:assert/strict";
import test from "node:test";
import { spawn, type ChildProcess } from "node:child_process";
import { createServer, type ServerResponse } from "node:http";
import { decodeX402, encodeX402 } from "../src/x402.js";

async function wait(url: string) { for (let i = 0; i < 50; i++) { try { await fetch(url); return; } catch { await new Promise((r) => setTimeout(r, 20)); } } throw new Error("server did not start"); }
function start(file: string, port: number, extra: Record<string, string> = {}): ChildProcess { return spawn(process.execPath, ["--import", "tsx", file], { cwd: process.cwd(), env: { ...process.env, PORT: String(port), ...extra }, stdio: "ignore" }); }
async function withProvider(facilitatorPort: number | undefined, run: (url: string) => Promise<void>, extra: Record<string, string> = {}) { const port = 35000 + Math.floor(Math.random() * 500); const provider = start("provider-demo/src/server.ts", port, { ...(facilitatorPort ? { FACILITATOR_URL: `http://127.0.0.1:${facilitatorPort}` } : { FACILITATOR_URL: "http://127.0.0.1:1" }), ...extra }); try { await wait(`http://127.0.0.1:${port}/events`); await run(`http://127.0.0.1:${port}`); } finally { provider.kill(); } }
async function withDouble(verify: unknown, settle: unknown, run: (port: number, counts: { verify: number; settle: number }) => Promise<void>) { const counts = { verify: 0, settle: 0 }; const port = 37000 + Math.floor(Math.random() * 500); const server = createServer((request, response: ServerResponse) => { const path = new URL(request.url ?? "/", "http://localhost").pathname; if (path === "/verify") { counts.verify++; response.writeHead(200, { "content-type": "application/json" }); response.end(JSON.stringify(verify)); return; } if (path === "/settle") { counts.settle++; response.writeHead(200, { "content-type": "application/json" }); response.end(JSON.stringify(settle)); return; } response.writeHead(404).end(); }); await new Promise<void>((resolve) => server.listen(port, "127.0.0.1", resolve)); try { await run(port, counts); } finally { await new Promise<void>((resolve) => server.close(() => resolve())); } }
async function paidRequest(url: string) { const first = await fetch(`${url}/execute`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ amount: 100, from: "USD", to: "ZAR" }) }); const required = decodeX402(first.headers.get("payment-required")!) as { accepts: [Record<string, unknown>] }; const accepted = required.accepts[0]; const payload = { x402Version: 2, accepted, payload: { simulation: { simulation: true, authorization: `SIMULATED_AUTHORIZATION:${accepted.amount}` } }, extensions: {} }; return fetch(`${url}/execute`, { method: "POST", headers: { "content-type": "application/json", "payment-signature": encodeX402(payload) }, body: JSON.stringify({ amount: 100, from: "USD", to: "ZAR" }) }); }
test("initial provider 402 is side-effect free and unavailable facilitator fails closed", async () => { await withProvider(undefined, async (url) => { const first = await fetch(`${url}/execute`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ amount: 100, from: "USD", to: "ZAR" }) }); assert.equal(first.status, 402); assert.ok(first.headers.get("payment-required")); assert.deepEqual(await (await fetch(`${url}/events`)).json(), { events: [], executionCount: 0 }); const failed = await paidRequest(url); assert.equal(failed.status, 503); assert.deepEqual(await (await fetch(`${url}/events`)).json(), { events: [], executionCount: 0 }); }); });
test("provider performs one verified paid execution then one settlement", async () => { const facPort = 36000 + Math.floor(Math.random() * 500); const facilitator = start("facilitator-demo/src/server.ts", facPort); try { await wait(`http://127.0.0.1:${facPort}/supported`); await withProvider(facPort, async (url) => { const response = await paidRequest(url); assert.equal(response.status, 200); assert.ok(response.headers.get("payment-response")); assert.deepEqual((await response.json() as { result: number; currency: string }), { result: 1850, currency: "ZAR", rate: 18.5, dataSource: "mock/test data", payment: { scheme: "exact", network: "eip155:84532", amount: "20000", asset: "simulation:usdc-base-sepolia", payTo: "simulation:independent-fx", maxTimeoutSeconds: 60, extra: { name: "USDC", version: "2", simulation: true }, status: "simulated_settled", simulation: true } }); assert.deepEqual(await (await fetch(`${url}/events`)).json(), { events: ["EXECUTE_ATTEMPT", "EXECUTE", "SETTLE_ATTEMPT", "SETTLE"], executionCount: 1 }); assert.deepEqual(await (await fetch(`http://127.0.0.1:${facPort}/events`)).json(), { events: ["VERIFY", "SETTLE"] }); }); } finally { facilitator.kill(); } });

test("provider fails closed for malformed verify and malformed or rejected settlement", async () => { for (const scenario of [{ verify: {}, settle: {}, status: 402, events: [], executions: 0, settles: 0 }, { verify: { isValid: true }, settle: {}, status: 502, events: ["EXECUTE_ATTEMPT", "EXECUTE", "SETTLE_ATTEMPT", "SETTLE_FAILURE"], executions: 1, settles: 1 }, { verify: { isValid: true }, settle: { success: false, errorReason: "invalid_payload", transaction: "", network: "eip155:84532" }, status: 502, events: ["EXECUTE_ATTEMPT", "EXECUTE", "SETTLE_ATTEMPT", "SETTLE_FAILURE"], executions: 1, settles: 1 }]) { await withDouble(scenario.verify, scenario.settle, async (port, counts) => { await withProvider(port, async (url) => { const response = await paidRequest(url); assert.equal(response.status, scenario.status); assert.equal(response.headers.get("payment-response"), null); const state = await (await fetch(`${url}/events`)).json() as { events: string[]; executionCount: number }; assert.deepEqual(state.events, scenario.events); assert.equal(state.executionCount, scenario.executions); assert.equal(counts.verify, 1); assert.equal(counts.settle, scenario.settles); }); }); } });
test("execution failure after verification does not settle", async () => { await withDouble({ isValid: true }, { success: true, transaction: "", network: "eip155:84532" }, async (port, counts) => { await withProvider(port, async (url) => { const response = await paidRequest(url); assert.equal(response.status, 400); assert.equal(response.headers.get("payment-response"), null); assert.deepEqual(await (await fetch(`${url}/events`)).json(), { events: ["EXECUTE_ATTEMPT", "EXECUTE_FAILURE"], executionCount: 0 }); assert.deepEqual(counts, { verify: 1, settle: 0 }); }, { SIMULATE_EXECUTION_FAILURE: "true" }); }); });
