import assert from "node:assert/strict"; import test from "node:test";
import { analyzeWebSearchSchema } from "../src/schema-compatibility.js"; import { decideCanonicalWebSearch } from "../src/classification.js"; import { normalizeX402DiscoveredResource } from "../src/external-discovery.js";
const input=(properties:object,required:string[]=[])=>( {type:"object",properties,required} );
const output=(collection:string, url:string="url")=>({type:"object",properties:{[collection]:{type:"array",items:{type:"object",properties:{[url]:{type:"string"},title:{type:"string"},description:{type:"string"}}}}}});
test("maps exact and renamed schemas without requiring optional limit",()=>{for(const [i,o] of [[input({query:{type:"string"}},["query"]),output("results")],[input({q:{type:"string"}},["q"]),output("items","link")],[input({search_query:{type:"string"},numResults:{type:"number"}},["search_query"]),output("organic","link")]] as const){const r=analyzeWebSearchSchema("fake",i,o);assert.equal(r.status,"compatible");assert.ok(r.adapterPlan);assert.ok(r.outputMappings.some(x=>x.canonicalPath==="results[].url"));} const r=analyzeWebSearchSchema("fake",input({query:{type:"string"}},["query"]),output("results"));assert.deepEqual(r.adapterPlan?.unsupportedCanonicalFields,["limit"]);});
test("rejects unmappable required native and credential inputs",()=>{for(const field of ["mandatoryAccountId","apiKey"]){const r=analyzeWebSearchSchema("fake",input({query:{type:"string"},[field]:{type:"string"}},["query",field]),output("results"));assert.equal(r.status,"incompatible");}});
test("keeps absent output and external refs incomplete, but answer-only output incompatible",()=>{assert.equal(analyzeWebSearchSchema("fake",input({query:{type:"string"}}),undefined).status,"partially_compatible");assert.equal(analyzeWebSearchSchema("fake",{$ref:"https://example.test/input"},{$ref:"https://example.test/output"}).status,"partially_compatible");assert.equal(analyzeWebSearchSchema("fake",input({query:{type:"string"}}),{properties:{answer:{type:"string"}}}).status,"incompatible");});
test("does not guess ambiguous text fields; supports nested, oneOf, and local defs",()=>{assert.equal(analyzeWebSearchSchema("fake",input({text:{type:"string"},prompt:{type:"string"}}),output("results")).status,"partially_compatible");const nested={type:"object",properties:{data:{type:"object",properties:output("results").properties}}};assert.equal(analyzeWebSearchSchema("fake",input({q:{type:"string"}}),nested).status,"compatible");const variants={oneOf:[input({q:{type:"string"}}),input({page:{type:"number"}})]};assert.equal(analyzeWebSearchSchema("fake",variants,output("items","href")).status,"compatible");const defs={type:"object",properties:{searchQuery:{$ref:"#/$defs/q"}},required:["searchQuery"],$defs:{q:{type:"string"}}};assert.equal(analyzeWebSearchSchema("fake",defs,output("matches","link")).status,"compatible");});
test("local recursive refs are bounded during output inspection",()=>{const recursive={type:"object",properties:{next:{$ref:"#/$defs/node"}},$defs:{node:{type:"object",properties:{next:{$ref:"#/$defs/node"}}}}};assert.equal(analyzeWebSearchSchema("fake",input({q:{type:"string"}}),recursive).status,"incompatible");});
function resource(description:string,inputSchema:object,outputSchema:object){return normalizeX402DiscoveredResource({resource:"https://unrelated.test/search",type:"http",x402Version:2,accepts:[{scheme:"exact",network:"eip155:1",amount:"1",asset:"a",payTo:"p",maxTimeoutSeconds:1}],lastUpdated:"2026-01-01T00:00:00Z",description,extensions:{bazaar:{info:{input:inputSchema,output:outputSchema}}}},"x","now")!;}
test("semantic scope remains the final gate despite compatible schemas",()=>{const schema=input({query:{type:"string"}},["query"]), out=output("results");for(const description of ["Search Twitter/X posts","Documentation search","Business directory search","Google Trends search","Package search","Internal private search","Site-specific search"])assert.equal(decideCanonicalWebSearch(resource(description,schema,out)).status,"rejected");assert.equal(decideCanonicalWebSearch(resource("Public web search",schema,out)).status,"matched");});
