import assert from "node:assert/strict";
import test from "node:test";
import { assessSelectionMeasurementComparability } from "../src/selection-measurement-comparability.js";
import type { SelectionMeasurementProjection } from "../src/selection-measurements.js";
const cap="web.search", asOf="2026-01-02T00:00:00.000Z";
function projection(providerId:string, patch:Partial<SelectionMeasurementProjection>={}) : SelectionMeasurementProjection { const base={status:"ESTABLISHED" as const,identity:{capabilityId:cap,providerId},request:{requiredMeasurements:["CANONICAL_SUCCESS"] as const},evidenceContext:{executionMode:"external" as const,observationCount:100,asOf,fromInclusive:"2026-01-01T00:00:00.000Z",toExclusive:asOf,spanMs:1000,contractState:"SINGLE_KNOWN" as const,contractFingerprint:"X",evidenceSufficiency:"SUFFICIENT" as const},canonicalOutput:{evaluationCount:100,successCount:98,failureCount:2,successRatio:.98},unavailableMeasurements:[],reasonCodes:[],provenance:{operationalEvidenceReasonCodes:[],missingEvidence:[],evidenceReference:{} as never}}; return {...base,...patch,identity:{...base.identity,...patch.identity},request:{...base.request,...patch.request},evidenceContext:{...base.evidenceContext,...patch.evidenceContext},canonicalOutput:patch.canonicalOutput===undefined?base.canonicalOutput:patch.canonicalOutput}; }
const assess=(ps:readonly SelectionMeasurementProjection[], req:Record<string,unknown>={})=>assessSelectionMeasurementComparability({capabilityId:cap,projections:ps,requirements:{measurementFamily:"CANONICAL_SUCCESS",...req}});
test("baseline compares established same-family measurements without inspecting values",()=>{const a=projection("a"),b=projection("b",{canonicalOutput:{evaluationCount:1000,successCount:990,failureCount:10,successRatio:.99}});const r=assess([b,a]);assert.equal(r.status,"COMPARABLE");assert.deepEqual(r.candidateContexts.map(x=>x.identity.providerId),["a","b"]);assert.equal(r.provenance.assessment,"BASELINE_MEASUREMENT_COMPARABILITY");});
test("empty, single, unavailable family, and upstream projection retain missing establishment",()=>{assert.equal(assess([]).status,"NOT_ESTABLISHED");assert.ok(assess([]).missingComparabilityFacts.includes("NO_MEASUREMENT_PROJECTIONS"));assert.ok(assess([projection("a")]).missingComparabilityFacts.includes("INSUFFICIENT_CANDIDATE_POPULATION"));assert.ok(assess([projection("a"),projection("b",{status:"NOT_ESTABLISHED"})]).missingComparabilityFacts.includes("PROJECTION_NOT_ESTABLISHED"));assert.ok(assess([projection("a"),projection("b",{request:{requiredMeasurements:["EXECUTION_SUCCESS"]}})]).missingComparabilityFacts.includes("REQUESTED_MEASUREMENT_UNAVAILABLE"));});
test("contract requirement distinguishes unknown from known difference",()=>{assert.equal(assess([projection("a"),projection("b")],{requireSameContractFingerprint:true}).status,"COMPARABLE");const differs=assess([projection("a"),projection("b",{evidenceContext:{contractFingerprint:"Y"}})],{requireSameContractFingerprint:true});assert.equal(differs.status,"NOT_COMPARABLE");assert.deepEqual(differs.failedComparabilityRequirements,["CONTRACT_FINGERPRINT_DIFFERS"]);const unknown=assess([projection("a"),projection("b",{evidenceContext:{contractState:"UNKNOWN",contractFingerprint:undefined}})],{requireSameContractFingerprint:true});assert.equal(unknown.status,"NOT_ESTABLISHED");});
test("asOf and window boundaries use exact population-wide thresholds",()=>{const later=projection("b",{evidenceContext:{asOf:"2026-01-02T00:00:01.000Z",toExclusive:"2026-01-02T00:00:01.000Z"}});assert.equal(assess([projection("a"),later],{maximumAsOfSkewMs:1000}).status,"COMPARABLE");assert.equal(assess([projection("a"),later],{maximumAsOfSkewMs:999}).status,"NOT_COMPARABLE");assert.equal(assess([projection("a"),later],{requireSameAsOf:true}).status,"NOT_COMPARABLE");assert.equal(assess([projection("a"),later],{requireSameWindowBounds:true}).status,"NOT_COMPARABLE");});
test("quantity is independently required with no pooling and missing precedence preserves failures",()=>{const low=projection("a",{canonicalOutput:{evaluationCount:10,successCount:9,failureCount:1,successRatio:.9}}),missingAsOf=projection("b",{evidenceContext:{asOf:"bad"}});const r=assess([low,missingAsOf],{minimumMeasurementSampleCountPerCandidate:20,maximumAsOfSkewMs:1});assert.equal(r.status,"NOT_ESTABLISHED");assert.ok(r.missingComparabilityFacts.includes("AS_OF_NOT_ESTABLISHED"));assert.ok(r.failedComparabilityRequirements.includes("MEASUREMENT_SAMPLE_COUNT_BELOW_REQUIREMENT"));});
test("validates atomically, preserves resource presence, and freezes detached results",()=>{const a=projection("a",{identity:{resourceId:""}}),b=projection("a");assert.equal(assess([a,b]).candidateCount,2);assert.throws(()=>assessSelectionMeasurementComparability({capabilityId:cap,projections:[projection("a"),projection("a")],requirements:{measurementFamily:"CANONICAL_SUCCESS"}}));assert.throws(()=>assess([projection("a"),projection("b")],{minimumObservationCountPerCandidate:1.5}));const input=[projection("a"),projection("b")];const r=assess(input);(input[0]!.evidenceContext as {observationCount:number}).observationCount=0;assert.equal(r.candidateContexts[0]!.observationCount,100);assert.throws(()=>{(r.candidateContexts as unknown as unknown[]).push({});});});
test("execution and latency families use their own retained denominators",()=>{const execution=(id:string,n:number):SelectionMeasurementProjection=>projection(id,{request:{requiredMeasurements:["EXECUTION_SUCCESS"]},execution:{attemptCount:n,successCount:n-1,failureCount:1,successRatio:(n-1)/n},canonicalOutput:undefined});const latency=(id:string,n:number,mean:number):SelectionMeasurementProjection=>projection(id,{request:{requiredMeasurements:["TRANSPORT_LATENCY"]},canonicalOutput:undefined,transportLatency:{sampleCount:n,minimumMs:1,maximumMs:mean*2,meanMs:mean}});assert.equal(assessSelectionMeasurementComparability({capabilityId:cap,projections:[execution("a",20),execution("b",200)],requirements:{measurementFamily:"EXECUTION_SUCCESS",minimumMeasurementSampleCountPerCandidate:20}}).status,"COMPARABLE");assert.equal(assessSelectionMeasurementComparability({capabilityId:cap,projections:[latency("a",20,50),latency("b",20,500)],requirements:{measurementFamily:"TRANSPORT_LATENCY"}}).status,"COMPARABLE");});
test("observation, window skew and span requirements independently preserve missing versus fail",()=>{const short=projection("a",{evidenceContext:{observationCount:19,spanMs:1000}}),long=projection("b",{evidenceContext:{observationCount:100,spanMs:2001,toExclusive:"2026-01-02T00:00:01.001Z"}});const r=assess([short,long],{minimumObservationCountPerCandidate:20,maximumWindowEndSkewMs:1000,maximumWindowSpanDifferenceMs:1000});assert.equal(r.status,"NOT_COMPARABLE");assert.ok(r.failedComparabilityRequirements.includes("OBSERVATION_COUNT_BELOW_REQUIREMENT"));assert.ok(r.failedComparabilityRequirements.includes("WINDOW_END_SKEW_EXCEEDED"));assert.ok(r.failedComparabilityRequirements.includes("WINDOW_SPAN_DIFFERENCE_EXCEEDED"));const absent=assess([projection("a"),projection("b",{evidenceContext:{spanMs:undefined}})],{maximumWindowSpanDifferenceMs:1});assert.equal(absent.status,"NOT_ESTABLISHED");});
test("baseline detects contradictory established simulation and canonical output is input-order independent",()=>{const bad=projection("a",{evidenceContext:{executionMode:"simulated"}}),good=projection("b");assert.equal(assess([bad,good]).status,"NOT_ESTABLISHED");const a=projection("a"),b=projection("b"),c=projection("c",{evidenceContext:{contractFingerprint:"Y"}}),requirements={requireSameContractFingerprint:true,minimumObservationCountPerCandidate:101};assert.deepEqual(assess([a,b,c],requirements),assess([c,a,b],requirements));});
test("population-wide skew, zero minima, and invalid family sample facts are conservative",()=>{const a=projection("a"),b=projection("b",{evidenceContext:{asOf:"2026-01-02T00:00:00.700Z"}}),c=projection("c",{evidenceContext:{asOf:"2026-01-02T00:00:01.400Z"}});assert.equal(assess([a,b,c],{maximumAsOfSkewMs:1000}).status,"NOT_COMPARABLE");assert.equal(assess([a,b],{minimumObservationCountPerCandidate:0,minimumMeasurementSampleCountPerCandidate:0}).status,"COMPARABLE");const malformed=projection("d",{canonicalOutput:{evaluationCount:NaN,successCount:0,failureCount:0,successRatio:NaN}});const missingAndFail=assess([a,c,projection("e",{evidenceContext:{asOf:"invalid"}}),malformed],{requireSameAsOf:true,minimumMeasurementSampleCountPerCandidate:1});assert.equal(missingAndFail.status,"NOT_ESTABLISHED");assert.ok(missingAndFail.failedComparabilityRequirements.includes("AS_OF_DIFFERS"));assert.ok(missingAndFail.missingComparabilityFacts.includes("AS_OF_NOT_ESTABLISHED"));assert.ok(missingAndFail.missingComparabilityFacts.includes("MEASUREMENT_SAMPLE_COUNT_NOT_ESTABLISHED"));});
