import assert from "node:assert/strict";
import test from "node:test";
import { createAppServer } from "../src/app.js";
import { WebSearchGateway, type WebSearchProviderAdapter } from "../src/web-search-gateway.js";

const clock={now:()=>new Date("2026-09-21T00:00:00.000Z")}; let n=0; const ids={next:()=>`request-${++n}`};
function provider(id:string, run:()=>Promise<unknown>, adapt:(x:unknown)=>unknown, cost=0.01, flags:Partial<WebSearchProviderAdapter>={}):WebSearchProviderAdapter{return {providerId:id,quotedCostUsd:cost,qualified:true,authorized:true,admissible:true,executeNative:run,adaptToCanonical:adapt,...flags};}
test("selects an admissible provider, adapts output, and records private operational facts",async()=>{const g=new WebSearchGateway([provider("a",async()=>({items:[{name:"A",link:"https://example.com/a"}]}),x=>({results:(x as any).items.map((i:any)=>({title:i.name,url:i.link}))}))],clock,ids);const r=await g.execute({capability:"web.search",input:{query:"secret query",limit:1}});assert.equal(r.ok,true);if(r.ok){assert.equal(r.output.results[0]!.url,"https://example.com/a");assert.equal(r.accounting.paymentStatus,"NOT_ENABLED");assert.ok(!JSON.stringify(r).includes("secret query"));}});
test("bounded fallback records both attempts and never runs an inadmissible provider",async()=>{let blocked=0;const g=new WebSearchGateway([provider("a",async()=>{throw new Error("down");},x=>x,0),provider("b",async()=>({hits:[{u:"https://example.com/b"}]}),x=>({results:(x as any).hits.map((i:any)=>({url:i.u}))}),.01),provider("blocked",async()=>{blocked++;return{};},x=>x,.02,{admissible:false})],clock,ids);const r=await g.execute({capability:"web.search",input:{query:"q"},policy:{maxProviderAttempts:2}});assert.equal(r.ok,true);if(r.ok)assert.deepEqual(r.accounting.attemptedProviders,["a","b"]);assert.equal(blocked,0);});
test("402 makes no payment and invalid output falls back",async()=>{let payment=0;const g=new WebSearchGateway([provider("pay",async()=>{throw {status:402};},x=>x,0)],clock,ids);const r=await g.execute({capability:"web.search",input:{query:"q"}});assert.equal(r.ok,false);if(!r.ok)assert.equal(r.error.code,"PAYMENT_REQUIRED_BY_PROVIDER");assert.equal(payment,0);const fallback=new WebSearchGateway([provider("bad",async()=>({results:[{url:"javascript:bad"}]}),x=>x,0),provider("good",async()=>({x:"https://example.com"}),x=>({results:[{url:(x as any).x}]}),.01)],clock,ids);assert.equal((await fallback.execute({capability:"web.search",input:{query:"q"}})).ok,true);});
test("no candidates and absent performance proof fail closed",async()=>{const none=new WebSearchGateway([],clock,ids);const a=await none.execute({capability:"web.search",input:{query:"q"}});assert.equal(a.ok,false);if(!a.ok)assert.equal(a.error.code,"NO_ADMISSIBLE_PROVIDER");const performance=new WebSearchGateway([provider("a",async()=>({results:[]}),x=>x)],clock,ids);const b=await performance.execute({capability:"web.search",input:{query:"q"},policy:{selection:"HIGHEST_CANONICAL_SUCCESS_RATIO"}});assert.equal(b.ok,false);if(!b.ok)assert.equal(b.error.code,"SELECTION_NOT_ESTABLISHED");});
test("HTTP endpoint exposes only the MVP canonical capability",async()=>{const gateway=new WebSearchGateway([provider("fixture",async()=>({r:["https://example.com"]}),x=>({results:(x as any).r.map((url:string)=>({url}))}))],clock,ids);const server=createAppServer(undefined,undefined,gateway);await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));const port=(server.address() as any).port;try{const response=await fetch(`http://127.0.0.1:${port}/v1/execute`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({capability:"web.search",input:{query:"news"}})});assert.equal(response.status,200);assert.equal((await response.json()).output.results.length,1);}finally{await new Promise<void>(resolve=>server.close(()=>resolve()));}});
