import test from "node:test"; import assert from "node:assert/strict";
import { encodeX402 } from "../src/x402.js"; import { constructSafeProbe, verifyX402Quote } from "../src/x402-quote-verification.js"; import type { NormalizedCapabilityProvider } from "../src/external-discovery.js";
const requirement={scheme:"exact",network:"eip155:1",amount:"10",asset:"USDC",payTo:"0xabc",maxTimeoutSeconds:30,extra:{}};
function resource(overrides:Partial<NormalizedCapabilityProvider>={}){return {providerId:"x",externalResourceId:"https://fixture.test/search",source:{ecosystem:"x402",sourceId:"https://bazaar.test",discoveredAt:"now",advertisedUpdatedAt:"2026-01-01T00:00:00Z"},invocation:{protocol:"x402",resource:"https://fixture.test/search",resourceType:"http"},economics:{paymentRequired:true,options:[requirement]},advertised:{description:"Search the public web",inputSchema:{type:"object",properties:{query:{type:"string"}},required:["query"]}},observed:{},x402:{invocation:{type:"http",method:"POST",placement:"jsonBody",parameters:{query:"example"}},bazaarSchema:{type:"object",properties:{input:{type:"object",properties:{body:{type:"object",properties:{query:{type:"string"}},required:["query"]}}}}}},...overrides} as NormalizedCapabilityProvider;}
const safe=async()=>({allowed:true as const,addresses:["203.0.113.2"]});
function challenge(req= requirement){return encodeX402({x402Version:2,error:"pay",resource:{url:"https://fixture.test/search"},accepts:[req],extensions:{}})}
async function verify(status:number,headers:Record<string,string>={},r=resource()){let calls=0;const answer=await verifyX402Quote(r,{validateEndpoint:safe,fetchImpl:(async()=>{calls++;return new Response("",{status,headers})}) as typeof fetch,now:()=>new Date("2026-01-02T00:00:00Z")});assert.equal(answer.requestCount,1);assert.equal(calls,1);return answer;}
test("matches an exact live quote and preserves the second advertised option",async()=>{let r=resource();const second={...requirement,amount:"20"};r={...r,economics:{paymentRequired:true,options:[requirement,second]}};const a=await verify(402,{"payment-required":challenge(second)},r);assert.equal(a.observed.status,"payment_required");assert.equal(a.comparison.matchedAdvertisedOption,1);assert.equal(a.comparison.amount,"match");});
for(const [field,value] of [["amount","11"],["network","eip155:2"],["asset","EURC"],["payTo","0xdef"]] as const)test(`reports ${field} quote discrepancy`,async()=>{const a=await verify(402,{"payment-required":challenge({...requirement,[field]:value})});assert.equal(a.comparison[field],"mismatch");assert.equal(a.comparison.matchedAdvertisedOption,undefined);});
test("rejects malformed PAYMENT-REQUIRED",async()=>assert.equal((await verify(402,{"payment-required":"bad"})).observed.status,"malformed_payment_challenge"));
for(const [code,status] of [[401,"authentication_required"],[403,"authentication_required"],[404,"not_found"],[405,"method_rejected"],[429,"rate_limited"],[500,"server_error"],[200,"reachable_without_payment"],[302,"redirect_response"],[400,"request_rejected"]] as const)test(`records HTTP ${code}`,async()=>assert.equal((await verify(code)).observed.status,status));
test("timeout is one request and never retries",async()=>{const a=await verifyX402Quote(resource(),{validateEndpoint:safe,fetchImpl:(async()=>{const e=new Error("aborted");e.name="AbortError";throw e;}) as typeof fetch});assert.equal(a.observed.status,"timeout");assert.equal(a.requestCount,1);});
test("unsafe endpoint is never contacted",async()=>{let calls=0;const a=await verifyX402Quote(resource(),{validateEndpoint:async()=>({allowed:false,reason:"private_ipv4"}),fetchImpl:(async()=>{calls++;return new Response()}) as typeof fetch});assert.equal(a.observed.status,"unsafe_endpoint");assert.equal(calls,0);assert.equal(a.requestCount,0);});
test("unknown required fields and side effects are never contacted",async()=>{for(const r of [resource({advertised:{inputSchema:{type:"object",properties:{account:{type:"string"}},required:["account"]}}}),resource({advertised:{description:"Purchase a thing",inputSchema:{type:"object",properties:{query:{type:"string"}},required:["query"]}}})]){let calls=0;const a=await verifyX402Quote(r,{validateEndpoint:safe,fetchImpl:(async()=>{calls++;return new Response()}) as typeof fetch});assert.ok(["probe_not_constructible","side_effect_risk"].includes(a.observed.status));assert.equal(calls,0);assert.equal(a.requestCount,0);}});
test("safe probe uses harmless query and deterministic minimum",()=>{const p=constructSafeProbe(resource({advertised:{inputSchema:{type:"object",properties:{query:{type:"string"},limit:{type:"integer",minimum:1}},required:["query","limit"]}}}));assert.deepEqual(p,{method:"POST",contentType:"application/json",body:{query:"OpenAI",limit:1}});});
