import { createServer, type IncomingMessage, type ServerResponse } from "node:http";

const supported = { kinds: [{ x402Version: 2, scheme: "exact", network: "eip155:84532" }], extensions: [], signers: {} };
const events: string[] = [];
function send(response: ServerResponse, status: number, value: unknown) { response.writeHead(status, { "content-type": "application/json" }); response.end(JSON.stringify(value)); }
async function body(request: IncomingMessage): Promise<unknown> { let text = ""; for await (const chunk of request) text += chunk; return JSON.parse(text); }
function record(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function valid(value: unknown): boolean { if (!record(value) || value.x402Version !== 2 || !record(value.paymentPayload) || !record(value.paymentRequirements)) return false; const payload = value.paymentPayload as Record<string, unknown>, req = value.paymentRequirements as Record<string, unknown>; const accepted = payload.accepted as Record<string, unknown> | undefined, inner = payload.payload as Record<string, unknown> | undefined, simulation = inner?.simulation as Record<string, unknown> | undefined; return ["scheme", "network", "amount", "asset", "payTo"].every((key) => accepted?.[key] === req[key]) && req.scheme === "exact" && req.network === "eip155:84532" && simulation?.simulation === true && simulation.authorization === `SIMULATED_AUTHORIZATION:${req.amount}`; }
const server = createServer(async (request, response) => { try { const path = new URL(request.url ?? "/", "http://localhost").pathname; if (request.method === "GET" && path === "/supported") return send(response, 200, supported); if (request.method === "GET" && path === "/events") return send(response, 200, { events }); if (request.method === "POST" && (path === "/verify" || path === "/settle")) { const input = await body(request); if (!valid(input)) { events.push(path === "/verify" ? "VERIFY_REJECTED" : "SETTLE_REJECTED"); return send(response, 200, path === "/verify" ? { isValid: false, invalidReason: "invalid_payload" } : { success: false, errorReason: "invalid_payload", transaction: "", network: "eip155:84532" }); } const requirement = (input as { paymentRequirements: { amount: string } }).paymentRequirements; if (path === "/verify") { events.push("VERIFY"); return send(response, 200, { isValid: true, extensions: { simulation: true } }); } events.push("SETTLE"); return send(response, 200, { success: true, transaction: "", network: "eip155:84532", amount: requirement.amount, extensions: { simulation: true } }); } return send(response, 404, { error: "Not found" }); } catch { return send(response, 400, { error: "Invalid request" }); } });
server.listen(Number(process.env.PORT ?? 3200), () => console.log("Simulated facilitator listening on http://localhost:3200"));
