/** Phase 12B: deterministic joining of supplied qualification and authorization populations. */
import { assessCandidateAdmissibility, type CandidateAdmissibilityResult, type CandidateIdentity } from "./candidate-admissibility.js";
import type { CapabilityQualificationResult } from "./capability-qualification.js";
import type { TransactionAuthorizationResult } from "./transaction-authorization.js";

export type CandidateSetJoinReason="AUTHORIZATION_RESULT_MISSING"|"QUALIFICATION_RESULT_MISSING"|"AMBIGUOUS_PARTIAL_IDENTITY_JOIN";
export interface CandidateAdmissibilitySetInput { readonly capabilityId:string; readonly qualifications:readonly CapabilityQualificationResult[]; readonly authorizations:readonly TransactionAuthorizationResult[]; }
export interface UnmatchedQualification { readonly identity:Readonly<CandidateIdentity>; readonly reasonCode:CandidateSetJoinReason; readonly qualification:CapabilityQualificationResult; }
export interface UnmatchedAuthorization { readonly identity:Readonly<CandidateIdentity>; readonly reasonCode:CandidateSetJoinReason; readonly authorization:TransactionAuthorizationResult; }
export interface JoinDiagnostic { readonly identity:Readonly<CandidateIdentity>; readonly side:"QUALIFICATION"|"AUTHORIZATION"; readonly reasonCode:CandidateSetJoinReason; }
export interface CandidateAdmissibilitySetResult { readonly capabilityId:string; readonly totalQualificationResults:number; readonly totalAuthorizationResults:number; readonly matchedPairCount:number; readonly admissible:readonly CandidateAdmissibilityResult[]; readonly notAdmissible:readonly CandidateAdmissibilityResult[]; readonly notEstablished:readonly CandidateAdmissibilityResult[]; readonly unmatchedQualifications:readonly UnmatchedQualification[]; readonly unmatchedAuthorizations:readonly UnmatchedAuthorization[]; readonly counts:Readonly<{admissible:number;notAdmissible:number;notEstablished:number;unmatchedQualifications:number;unmatchedAuthorizations:number}>; readonly joinDiagnostics:readonly JoinDiagnostic[]; }
type Upstream=CapabilityQualificationResult|TransactionAuthorizationResult;
function freeze<T>(x:T):T {if(x&&typeof x==="object"&&!Object.isFrozen(x)){Object.freeze(x);for(const v of Object.values(x as Record<string,unknown>))freeze(v);}return x;}
function snap<T>(x:T):T{return freeze(structuredClone(x));}
function identity(x:Upstream):CandidateIdentity{return {capabilityId:x.capabilityId,providerId:x.providerId,...(x.resourceId===undefined?{}:{resourceId:x.resourceId})};}
function key(x:Upstream):string{return JSON.stringify([x.capabilityId,x.providerId,Object.hasOwn(x,"resourceId"),x.resourceId]);}
function group(x:Upstream):string{return JSON.stringify([x.capabilityId,x.providerId]);}
function compareIdentity(a:CandidateIdentity,b:CandidateIdentity):number {const base=a.capabilityId.localeCompare(b.capabilityId)||a.providerId.localeCompare(b.providerId);if(base)return base;const ah=Object.hasOwn(a,"resourceId"),bh=Object.hasOwn(b,"resourceId");return ah===bh?String(a.resourceId??"").localeCompare(String(b.resourceId??"")):ah?1:-1;}
function validate(input:CandidateAdmissibilitySetInput):void {if(!input||!input.capabilityId||!Array.isArray(input.qualifications)||!Array.isArray(input.authorizations))throw new Error("capabilityId, qualifications, and authorizations are required");const inspect=(values:readonly Upstream[],duplicate:string)=>{const seen=new Set<string>();for(const value of values){if(!value||value.capabilityId!==input.capabilityId)throw new Error("INCONSISTENT_SET_CAPABILITY");if(!value.providerId)throw new Error("CANDIDATE_PROVIDER_ID_REQUIRED");const k=key(value);if(seen.has(k))throw new Error(duplicate);seen.add(k);}};inspect(input.qualifications,"DUPLICATE_QUALIFICATION_IDENTITY");inspect(input.authorizations,"DUPLICATE_AUTHORIZATION_IDENTITY");}
/** Exact resource identity wins; optional-resource matching occurs only for a unique remaining pair. */
export function formAdmissibleCandidateSet(input:CandidateAdmissibilitySetInput):CandidateAdmissibilitySetResult {
 validate(input);const qs=[...input.qualifications],as=[...input.authorizations],usedQ=new Set<number>(),usedA=new Set<number>(),pairs:[number,number][]=[];
 for(let qi=0;qi<qs.length;qi++)for(let ai=0;ai<as.length;ai++)if(!usedQ.has(qi)&&!usedA.has(ai)&&key(qs[qi]!)===key(as[ai]!)){usedQ.add(qi);usedA.add(ai);pairs.push([qi,ai]);}
 const ambiguousQ=new Set<number>(),ambiguousA=new Set<number>();const groups=new Set([...qs.filter((_,i)=>!usedQ.has(i)).map(group),...as.filter((_,i)=>!usedA.has(i)).map(group)]);
 for(const g of groups){const qi=qs.map((x,i)=>[x,i] as const).filter(([x,i])=>!usedQ.has(i)&&group(x)===g),ai=as.map((x,i)=>[x,i] as const).filter(([x,i])=>!usedA.has(i)&&group(x)===g),edges:[number,number][]=[];for(const [q,i] of qi)for(const [a,j] of ai)if((q.resourceId===undefined)!==(a.resourceId===undefined))edges.push([i,j]);if(edges.length===1){usedQ.add(edges[0]![0]);usedA.add(edges[0]![1]);pairs.push(edges[0]!);}else if(edges.length>1)for(const [i,j] of edges){ambiguousQ.add(i);ambiguousA.add(j);}}
 const matched=pairs.map(([i,j])=>assessCandidateAdmissibility({qualification:qs[i]!,authorization:as[j]!})).sort((a,b)=>compareIdentity(a.identity,b.identity));
 const unmatchedQualifications=qs.map((q,i)=>({q,i})).filter(x=>!usedQ.has(x.i)).map(({q,i})=>freeze({identity:freeze(identity(q)),reasonCode:(ambiguousQ.has(i)?"AMBIGUOUS_PARTIAL_IDENTITY_JOIN":"AUTHORIZATION_RESULT_MISSING") as CandidateSetJoinReason,qualification:snap(q)})).sort((a,b)=>compareIdentity(a.identity,b.identity)||a.reasonCode.localeCompare(b.reasonCode));
 const unmatchedAuthorizations=as.map((a,i)=>({a,i})).filter(x=>!usedA.has(x.i)).map(({a,i})=>freeze({identity:freeze(identity(a)),reasonCode:(ambiguousA.has(i)?"AMBIGUOUS_PARTIAL_IDENTITY_JOIN":"QUALIFICATION_RESULT_MISSING") as CandidateSetJoinReason,authorization:snap(a)})).sort((a,b)=>compareIdentity(a.identity,b.identity)||a.reasonCode.localeCompare(b.reasonCode));
 const diagnostics=[...unmatchedQualifications.map(x=>freeze({identity:x.identity,side:"QUALIFICATION" as const,reasonCode:x.reasonCode})),...unmatchedAuthorizations.map(x=>freeze({identity:x.identity,side:"AUTHORIZATION" as const,reasonCode:x.reasonCode}))].sort((a,b)=>compareIdentity(a.identity,b.identity)||a.side.localeCompare(b.side)||a.reasonCode.localeCompare(b.reasonCode));
 const admissible=matched.filter(x=>x.status==="ADMISSIBLE"),notAdmissible=matched.filter(x=>x.status==="NOT_ADMISSIBLE"),notEstablished=matched.filter(x=>x.status==="NOT_ESTABLISHED");if(admissible.length+notAdmissible.length+notEstablished.length!==matched.length)throw new Error("MATCHED_PARTITION_INVARIANT");if(matched.length+unmatchedQualifications.length!==qs.length||matched.length+unmatchedAuthorizations.length!==as.length)throw new Error("SET_ACCOUNTING_INVARIANT");const counts=freeze({admissible:admissible.length,notAdmissible:notAdmissible.length,notEstablished:notEstablished.length,unmatchedQualifications:unmatchedQualifications.length,unmatchedAuthorizations:unmatchedAuthorizations.length});return freeze({capabilityId:input.capabilityId,totalQualificationResults:qs.length,totalAuthorizationResults:as.length,matchedPairCount:matched.length,admissible:freeze(admissible),notAdmissible:freeze(notAdmissible),notEstablished:freeze(notEstablished),unmatchedQualifications:freeze(unmatchedQualifications),unmatchedAuthorizations:freeze(unmatchedAuthorizations),counts,joinDiagnostics:freeze(diagnostics)});
}
