import { qualifyCandidateSet, type CandidateSetQualificationInput, type CandidateKey } from "./candidate-qualification-set.js";
import type { CapabilityQualificationInput } from "./capability-qualification.js";
const requirement={requireSemanticMatch:true,requireSchemaCompatibility:true,requireExternalCanonicalSuccess:true,requireOperationalEvidence:true,requireOperationalAcceptance:true};
const candidate=(providerId:string, patch:Partial<CapabilityQualificationInput>={}):CapabilityQualificationInput=>{
 const id={capabilityId:"web.search",providerId,resourceId:`synthetic://${providerId}`}; const semantic=(status:"matched"|"rejected")=>({capabilityId:"web.search" as const,resourceId:id.resourceId,status,confidence:1,evidence:[],missingEvidence:[],rejectionReasons:[]});
 const schema=(status:"compatible"|"incompatible")=>({status,inputMappings:[],outputMappings:[],transformations:[],evidence:[],missingRequirements:[],incompatibilities:[]}); const state={...id,facts:{externalCanonicalSuccessObserved:true,externalCanonicalIncompatibleObserved:false},provenance:{observedCount:1,observedAt:[]}};
 return {...id,semanticClassification:semantic("matched"),schemaCompatibility:schema("compatible"),capabilityEvidenceState:state as any,operationalEvidenceAssessment:{status:"sufficient",evidenceReference:id} as any,operationalAcceptanceAssessment:{status:"ACCEPTED",evidenceReference:id} as any,...patch};
};
const set:CandidateSetQualificationInput={capabilityId:"web.search",requirement,candidates:[candidate("A"),candidate("B"),candidate("C",{operationalAcceptanceAssessment:{status:"REJECTED",evidenceReference:{capabilityId:"web.search",providerId:"C",resourceId:"synthetic://C"}} as any}),candidate("D",{schemaCompatibility:{status:"incompatible",inputMappings:[],outputMappings:[],transformations:[],evidence:[],missingRequirements:[],incompatibilities:[]}}),candidate("E",{operationalEvidenceAssessment:{status:"insufficient",evidenceReference:{capabilityId:"web.search",providerId:"E",resourceId:"synthetic://E"}} as any,operationalAcceptanceAssessment:{status:"NOT_EVALUATED",evidenceReference:{capabilityId:"web.search",providerId:"E",resourceId:"synthetic://E"}} as any}),candidate("F",{capabilityEvidenceState:{...candidate("F").capabilityEvidenceState!,facts:{externalCanonicalSuccessObserved:false,externalCanonicalIncompatibleObserved:false}} as any}),candidate("G",{semanticClassification:{...candidate("G").semanticClassification!,status:"rejected"},operationalEvidenceAssessment:{status:"insufficient",evidenceReference:{capabilityId:"web.search",providerId:"G",resourceId:"synthetic://G"}} as any,operationalAcceptanceAssessment:{status:"NOT_EVALUATED",evidenceReference:{capabilityId:"web.search",providerId:"G",resourceId:"synthetic://G"}} as any}),candidate("H",{operationalAcceptanceAssessment:{status:"NOT_EVALUATED",evidenceReference:{capabilityId:"web.search",providerId:"H",resourceId:"synthetic://H"}} as any})]};
const show=(x:CandidateKey)=>`${x.providerId}${x.resourceId?`/${x.resourceId}`:""}`; const result=qualifyCandidateSet(set);
console.log("Phase 11E candidate-set qualification (offline synthetic evidence only)"); console.log("TOTAL CANDIDATES",result.totalCandidates);
for(const [name,values] of [["QUALIFIED",result.qualified],["NOT QUALIFIED",result.notQualified],["NOT ESTABLISHED",result.notEstablished]] as const) console.log(name,values.length,values.map(show));
console.log("EVIDENCE GAPS"); for(const x of result.evidenceGaps) console.log(x.dimension,x.reasonCode,x.candidateCount,x.candidateKeys.map(show));
console.log("ESTABLISHED FAILURES"); for(const x of result.establishedFailures) console.log(x.dimension,x.reasonCode,x.candidateCount,x.candidateKeys.map(show));
const pooled=qualifyCandidateSet({capabilityId:"web.search",requirement:{requireOperationalEvidence:true},candidates:[candidate("pool-A",{operationalEvidenceAssessment:{status:"insufficient",evidenceReference:{capabilityId:"web.search",providerId:"pool-A",resourceId:"synthetic://pool-A"}} as any}),candidate("pool-B",{operationalEvidenceAssessment:{status:"insufficient",evidenceReference:{capabilityId:"web.search",providerId:"pool-B",resourceId:"synthetic://pool-B"}} as any})]});
console.log("NO CROSS-CANDIDATE POOLING: Provider A 10 attempts; Provider B 10 attempts; minimum required 20 per candidate"); console.log(pooled.notEstablished.map(x=>`${x.providerId} ${x.status}`));
