import type { NormalizedCapabilityProvider } from "./external-discovery.js";
import { validatePublicHttps, type NetworkSafetyReason } from "./network-safety.js";
export type InspectionStatus="success"|"unreachable"|"timeout"|"invalid_protocol"|"authentication_required"|"payment_required"|"unsupported_transport"|"unsafe_endpoint"|"malformed_response";
export interface InspectedCapability {protocol:"mcp";nativeName:string;description?:string;inputSchema:Record<string,unknown>;outputSchema?:Record<string,unknown>;metadata?:Record<string,unknown>}
export interface CapabilityInspectionResult {resourceId:string;inspectedAt:string;status:InspectionStatus;capabilities:InspectedCapability[];diagnostics:string[];protocolVersion?:string;safetyReason?:NetworkSafetyReason}
export interface CapabilityInspector {inspect(resource:NormalizedCapabilityProvider):Promise<CapabilityInspectionResult>}
export class MCPRemoteCapabilityInspector implements CapabilityInspector {constructor(private readonly opts:{fetchImpl?:typeof fetch;allowUnsafeForTest?:boolean;maxPages?:number;timeoutMs?:number;now?:()=>Date;resolver?:any}={}){}
 async inspect(r:NormalizedCapabilityProvider):Promise<CapabilityInspectionResult>{const at=(this.opts.now??(()=>new Date()))().toISOString();const remote=r.mcp?.remotes.find(x=>x.type==="streamable-http"&&typeof x.url==="string");const base={resourceId:r.externalResourceId,inspectedAt:at,capabilities:[] as InspectedCapability[],diagnostics:[] as string[]};if(!remote||typeof remote.url!=="string")return{...base,status:"unsupported_transport"};const check=this.opts.allowUnsafeForTest?{allowed:true}:await validatePublicHttps(remote.url as string,this.opts.resolver);if(!check.allowed)return{...base,status:"unsafe_endpoint",safetyReason:check.reason,diagnostics:[check.reason??"unsafe endpoint"]};let id=1,version="2025-11-25",session="";const post=async(method:string,params?:Record<string,unknown>)=>{const c=new AbortController(),t=setTimeout(()=>c.abort(),this.opts.timeoutMs??5000);try{return await (this.opts.fetchImpl??fetch)(remote.url as string,{method:"POST",redirect:"error",signal:c.signal,headers:{"content-type":"application/json","accept":"application/json, text/event-stream","mcp-protocol-version":version,"mcp-method":method,...(session?{"mcp-session-id":session}:{})},body:JSON.stringify({jsonrpc:"2.0",...(method.startsWith("notifications/")?{}:{id:id++}),method,...(params?{params}:{})})})}finally{clearTimeout(t)}};
 try {const endpoint=remote.url as string;let res=await post("initialize",{protocolVersion:version,capabilities:{},clientInfo:{name:"capability-inspector",version:"0.1"}});if(res.status===401||res.status===403)return{...base,status:"authentication_required"};if(res.status===402)return{...base,status:"payment_required"};if(!res.ok)return{...base,status:"unreachable",diagnostics:[`HTTP ${res.status}`]};session=res.headers.get("mcp-session-id")??"";const init=await res.json() as any;if(!init?.result?.protocolVersion)return{...base,status:"invalid_protocol"};version=init.result.protocolVersion;await post("notifications/initialized");let cursor:unknown, pages=0;while(pages++<(this.opts.maxPages??3)){res=await post("tools/list",cursor===undefined?undefined:{cursor});if(res.status===401||res.status===403)return{...base,status:"authentication_required",protocolVersion:version};if(res.status===402)return{...base,status:"payment_required",protocolVersion:version};if(!res.ok)return{...base,status:"unreachable",protocolVersion:version};const body=await res.json() as any;if(!Array.isArray(body?.result?.tools))return{...base,status:"malformed_response",protocolVersion:version};for(const tool of body.result.tools){if(typeof tool?.name!=="string"||!tool.inputSchema||typeof tool.inputSchema!=="object")return{...base,status:"malformed_response",protocolVersion:version};base.capabilities.push({protocol:"mcp",nativeName:tool.name,description:typeof tool.description==="string"?tool.description:undefined,inputSchema:tool.inputSchema,outputSchema:tool.outputSchema,metadata:tool._meta})}cursor=body.result.nextCursor;if(typeof cursor!=="string")break}return{...base,status:"success",protocolVersion:version}}catch(e){return{...base,status:e instanceof Error&&e.name==="AbortError"?"timeout":"unreachable"}}}
}


