import type { SelectionMeasurementFamily, SelectionMeasurementProjection } from "./selection-measurements.js";

export type SelectionMeasurementComparabilityStatus = "COMPARABLE" | "NOT_COMPARABLE" | "NOT_ESTABLISHED";
export type ComparabilityDimensionState = "ESTABLISHED_PASS" | "ESTABLISHED_FAIL" | "NOT_ESTABLISHED" | "NOT_REQUIRED";
export type ComparabilityDimensionName = "MEASUREMENT_FAMILY" | "EXECUTION_MODE" | "CONTRACT_CONTEXT" | "AS_OF_ALIGNMENT" | "WINDOW_ALIGNMENT" | "OBSERVATION_QUANTITY" | "MEASUREMENT_SAMPLE_QUANTITY";
export interface SelectionMeasurementComparabilityRequirements {
  readonly measurementFamily: SelectionMeasurementFamily;
  readonly requireExternalExecutionMode?: boolean;
  readonly requireSameContractFingerprint?: boolean;
  readonly requireSingleKnownContract?: boolean;
  readonly requireSameAsOf?: boolean;
  readonly maximumAsOfSkewMs?: number;
  readonly requireSameWindowBounds?: boolean;
  readonly maximumWindowEndSkewMs?: number;
  readonly maximumWindowSpanDifferenceMs?: number;
  readonly minimumObservationCountPerCandidate?: number;
  readonly minimumMeasurementSampleCountPerCandidate?: number;
}
export interface SelectionMeasurementComparabilityInput { readonly capabilityId: string; readonly projections: readonly SelectionMeasurementProjection[]; readonly requirements: SelectionMeasurementComparabilityRequirements; }
export interface SelectionMeasurementComparabilityDimension { readonly dimension: ComparabilityDimensionName; readonly state: ComparabilityDimensionState; readonly reasonCodes: readonly string[]; }
export interface SelectionMeasurementCandidateContext {
  readonly identity: Readonly<{ capabilityId: string; providerId: string; resourceId?: string }>;
  readonly measurementFamily: SelectionMeasurementFamily; readonly measurement: Readonly<Record<string, number>>;
  readonly sampleCount?: number; readonly observationCount: number; readonly executionMode: "external" | "simulated";
  readonly asOf: string; readonly fromInclusive?: string; readonly toExclusive?: string; readonly spanMs?: number;
  readonly contractState: SelectionMeasurementProjection["evidenceContext"]["contractState"]; readonly contractFingerprint?: string;
}
export interface SelectionMeasurementComparabilityResult {
  readonly status: SelectionMeasurementComparabilityStatus; readonly capabilityId: string; readonly measurementFamily: SelectionMeasurementFamily; readonly candidateCount: number;
  readonly requirements: Readonly<SelectionMeasurementComparabilityRequirements>; readonly dimensions: readonly SelectionMeasurementComparabilityDimension[];
  readonly candidateContexts: readonly SelectionMeasurementCandidateContext[]; readonly missingComparabilityFacts: readonly string[]; readonly failedComparabilityRequirements: readonly string[]; readonly reasonCodes: readonly string[];
  readonly provenance: Readonly<{ assessment: "BASELINE_MEASUREMENT_COMPARABILITY"; projectionStatuses: readonly SelectionMeasurementProjection["status"][] }>;
}
const families: readonly SelectionMeasurementFamily[]=["EXECUTION_SUCCESS","CANONICAL_SUCCESS","TRANSPORT_LATENCY"];
const dimensionOrder: readonly ComparabilityDimensionName[]=["MEASUREMENT_FAMILY","EXECUTION_MODE","CONTRACT_CONTEXT","AS_OF_ALIGNMENT","WINDOW_ALIGNMENT","OBSERVATION_QUANTITY","MEASUREMENT_SAMPLE_QUANTITY"];
const missingReasonCodes=new Set(["NO_MEASUREMENT_PROJECTIONS","INSUFFICIENT_CANDIDATE_POPULATION","PROJECTION_NOT_ESTABLISHED","REQUESTED_MEASUREMENT_UNAVAILABLE","INCONSISTENT_UPSTREAM_PROJECTION","CONTRACT_CONTEXT_NOT_ESTABLISHED","AS_OF_NOT_ESTABLISHED","WINDOW_BOUNDS_NOT_ESTABLISHED","WINDOW_SPAN_NOT_ESTABLISHED","OBSERVATION_COUNT_NOT_ESTABLISHED","MEASUREMENT_SAMPLE_COUNT_NOT_ESTABLISHED"]);
const freeze=<T>(value:T):T=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value as Record<string,unknown>))freeze(child);}return value;};
const snapshot=<T>(value:T):T=>freeze(structuredClone(value));
const has=(o:object,k:string)=>Object.prototype.hasOwnProperty.call(o,k);
function key(i:{capabilityId:string;providerId:string;resourceId?:string}) { return `${i.capabilityId.length}:${i.capabilityId}|${i.providerId.length}:${i.providerId}|${has(i,"resourceId")?`1:${i.resourceId!.length}:${i.resourceId}`:"0"}`; }
function validTime(value:string):number|undefined { if(!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(value))return undefined; const n=Date.parse(value); return Number.isFinite(n)&&new Date(n).toISOString()===value?n:undefined; }
function sample(p:SelectionMeasurementProjection,f:SelectionMeasurementFamily): {count?:number; measurement:Record<string,number>} {
  if(f==="EXECUTION_SUCCESS"&&p.execution)return {count:p.execution.attemptCount,measurement:{numerator:p.execution.successCount,denominator:p.execution.attemptCount,ratio:p.execution.successRatio}};
  if(f==="CANONICAL_SUCCESS"&&p.canonicalOutput)return {count:p.canonicalOutput.evaluationCount,measurement:{numerator:p.canonicalOutput.successCount,denominator:p.canonicalOutput.evaluationCount,ratio:p.canonicalOutput.successRatio}};
  if(f==="TRANSPORT_LATENCY"&&p.transportLatency)return {count:p.transportLatency.sampleCount,measurement:{sampleCount:p.transportLatency.sampleCount,minimumMs:p.transportLatency.minimumMs,maximumMs:p.transportLatency.maximumMs,meanMs:p.transportLatency.meanMs}};
  return {measurement:{}};
}
function state(name:ComparabilityDimensionName, required:boolean, missing:string[], failed:string[]):SelectionMeasurementComparabilityDimension { return {dimension:name,state:!required?"NOT_REQUIRED":missing.length?"NOT_ESTABLISHED":failed.length?"ESTABLISHED_FAIL":"ESTABLISHED_PASS",reasonCodes:[...missing,...failed]}; }
function validate(input:SelectionMeasurementComparabilityInput):void { if(!input||typeof input.capabilityId!=="string"||!Array.isArray(input.projections)||!input.requirements||!families.includes(input.requirements.measurementFamily))throw new Error("capabilityId, projections, and a known measurementFamily are required"); const r=input.requirements as unknown as Record<string,unknown>; for(const n of ["maximumAsOfSkewMs","maximumWindowEndSkewMs","maximumWindowSpanDifferenceMs","minimumObservationCountPerCandidate","minimumMeasurementSampleCountPerCandidate"]){if(r[n]!==undefined&&(!Number.isFinite(r[n])||typeof r[n]!=="number"||r[n]<0||(n.startsWith("minimum")&&!Number.isSafeInteger(r[n]))))throw new Error(`invalid ${n}`);} if(r.requireSameAsOf===true&&r.maximumAsOfSkewMs!==undefined)throw new Error("requireSameAsOf and maximumAsOfSkewMs cannot both be supplied"); for(const b of ["requireExternalExecutionMode","requireSameContractFingerprint","requireSingleKnownContract","requireSameAsOf","requireSameWindowBounds"])if(r[b]!==undefined&&typeof r[b]!=="boolean")throw new Error(`invalid ${b}`); const ids=new Set<string>();for(const p of input.projections){if(!p?.identity||p.identity.capabilityId!==input.capabilityId)throw new Error("projection capability does not match declared capabilityId");const k=key(p.identity);if(ids.has(k))throw new Error("duplicate projection identity");ids.add(k);} }

/** Pure population-wide evidence-context assessment. It never orders measurement values or selects a candidate. */
export function assessSelectionMeasurementComparability(input:SelectionMeasurementComparabilityInput):SelectionMeasurementComparabilityResult {
  validate(input); const r=input.requirements, f=r.measurementFamily, projections=[...input.projections].sort((a,b)=>key(a.identity).localeCompare(key(b.identity)));
  const contexts=projections.map(p=>{const s=sample(p,f),e=p.evidenceContext;return {identity:{...p.identity},measurementFamily:f,measurement:s.measurement,...(s.count===undefined?{}:{sampleCount:s.count}),observationCount:e.observationCount,executionMode:e.executionMode,asOf:e.asOf,...(e.fromInclusive===undefined?{}:{fromInclusive:e.fromInclusive}),...(e.toExclusive===undefined?{}:{toExclusive:e.toExclusive}),...(e.spanMs===undefined?{}:{spanMs:e.spanMs}),contractState:e.contractState,...(e.contractFingerprint===undefined?{}:{contractFingerprint:e.contractFingerprint})};});
  const dims:SelectionMeasurementComparabilityDimension[]=[];
  const familyMissing:string[]=[]; if(!projections.length)familyMissing.push("NO_MEASUREMENT_PROJECTIONS"); if(projections.length===1)familyMissing.push("INSUFFICIENT_CANDIDATE_POPULATION"); if(projections.some(p=>p.status!=="ESTABLISHED"))familyMissing.push("PROJECTION_NOT_ESTABLISHED"); if(projections.some((p,i)=>!p.request.requiredMeasurements.includes(f)||contexts[i]!.sampleCount===undefined))familyMissing.push("REQUESTED_MEASUREMENT_UNAVAILABLE"); dims.push(state("MEASUREMENT_FAMILY",true,familyMissing,[]));
  const executionRequired=r.requireExternalExecutionMode!==false; const executionMissing:string[]=[]; if(executionRequired&&projections.some(p=>p.evidenceContext.executionMode!=="external"||p.evidenceContext.evidenceSufficiency!=="SUFFICIENT"))executionMissing.push("INCONSISTENT_UPSTREAM_PROJECTION"); dims.push(state("EXECUTION_MODE",executionRequired,executionMissing,[]));
  const contractRequired=r.requireSingleKnownContract===true||r.requireSameContractFingerprint===true, contractMissing:string[]=[],contractFailed:string[]=[]; if(contractRequired){if(projections.some(p=>p.evidenceContext.contractState!=="SINGLE_KNOWN"||!p.evidenceContext.contractFingerprint))contractMissing.push("CONTRACT_CONTEXT_NOT_ESTABLISHED");else if(r.requireSameContractFingerprint&&new Set(projections.map(p=>p.evidenceContext.contractFingerprint)).size>1)contractFailed.push("CONTRACT_FINGERPRINT_DIFFERS");} dims.push(state("CONTRACT_CONTEXT",contractRequired,contractMissing,contractFailed));
  const asOfRequired=r.requireSameAsOf===true||r.maximumAsOfSkewMs!==undefined, asOfMissing:string[]=[],asOfFailed:string[]=[]; let asOfs:number[]=[];if(asOfRequired){asOfs=projections.map(p=>validTime(p.evidenceContext.asOf)??NaN);const known=asOfs.filter(Number.isFinite);if(asOfs.some(Number.isNaN))asOfMissing.push("AS_OF_NOT_ESTABLISHED");if(r.requireSameAsOf&&new Set(known).size>1)asOfFailed.push("AS_OF_DIFFERS");if(r.maximumAsOfSkewMs!==undefined&&known.length>1&&Math.max(...known)-Math.min(...known)>r.maximumAsOfSkewMs)asOfFailed.push("AS_OF_SKEW_EXCEEDED");}dims.push(state("AS_OF_ALIGNMENT",asOfRequired,asOfMissing,asOfFailed));
  const windowRequired=r.requireSameWindowBounds===true||r.maximumWindowEndSkewMs!==undefined||r.maximumWindowSpanDifferenceMs!==undefined,windowMissing:string[]=[],windowFailed:string[]=[];if(windowRequired){const bounds=projections.map(p=>({from:validTime(p.evidenceContext.fromInclusive??""),to:validTime(p.evidenceContext.toExclusive??"")}));if(r.requireSameWindowBounds){const known=bounds.filter((x):x is {from:number;to:number}=>x.from!==undefined&&x.to!==undefined);if(known.length!==bounds.length)windowMissing.push("WINDOW_BOUNDS_NOT_ESTABLISHED");if(new Set(known.map(x=>`${x.from}|${x.to}`)).size>1)windowFailed.push("WINDOW_BOUNDS_DIFFER");}if(r.maximumWindowEndSkewMs!==undefined){const ends=bounds.map(x=>x.to).filter((x):x is number=>x!==undefined);if(ends.length!==bounds.length)windowMissing.push("WINDOW_BOUNDS_NOT_ESTABLISHED");if(ends.length>1&&Math.max(...ends)-Math.min(...ends)>r.maximumWindowEndSkewMs)windowFailed.push("WINDOW_END_SKEW_EXCEEDED");}if(r.maximumWindowSpanDifferenceMs!==undefined){const spans=projections.map(p=>p.evidenceContext.spanMs),known=spans.filter((x):x is number=>typeof x==="number"&&Number.isFinite(x)&&x>=0);if(known.length!==spans.length)windowMissing.push("WINDOW_SPAN_NOT_ESTABLISHED");if(known.length>1&&Math.max(...known)-Math.min(...known)>r.maximumWindowSpanDifferenceMs)windowFailed.push("WINDOW_SPAN_DIFFERENCE_EXCEEDED");}}dims.push(state("WINDOW_ALIGNMENT",windowRequired,[...new Set(windowMissing)],[...new Set(windowFailed)]));
  const observationRequired=r.minimumObservationCountPerCandidate!==undefined,obsMissing:string[]=[],obsFailed:string[]=[];if(observationRequired){if(projections.some(p=>!Number.isSafeInteger(p.evidenceContext.observationCount)||p.evidenceContext.observationCount<0))obsMissing.push("OBSERVATION_COUNT_NOT_ESTABLISHED");else if(projections.some(p=>p.evidenceContext.observationCount<r.minimumObservationCountPerCandidate!))obsFailed.push("OBSERVATION_COUNT_BELOW_REQUIREMENT");}dims.push(state("OBSERVATION_QUANTITY",observationRequired,obsMissing,obsFailed));
  const sampleRequired=r.minimumMeasurementSampleCountPerCandidate!==undefined,sampleMissing:string[]=[],sampleFailed:string[]=[];if(sampleRequired){if(contexts.some(c=>!Number.isSafeInteger(c.sampleCount)||c.sampleCount!<0))sampleMissing.push("MEASUREMENT_SAMPLE_COUNT_NOT_ESTABLISHED");else if(contexts.some(c=>c.sampleCount!<r.minimumMeasurementSampleCountPerCandidate!))sampleFailed.push("MEASUREMENT_SAMPLE_COUNT_BELOW_REQUIREMENT");}dims.push(state("MEASUREMENT_SAMPLE_QUANTITY",sampleRequired,sampleMissing,sampleFailed));
  const allReasons=dims.flatMap(d=>d.reasonCodes),missing=allReasons.filter(code=>missingReasonCodes.has(code)),failed=allReasons.filter(code=>!missingReasonCodes.has(code)),status:SelectionMeasurementComparabilityStatus=missing.length?"NOT_ESTABLISHED":failed.length?"NOT_COMPARABLE":"COMPARABLE";
  return snapshot({status,capabilityId:input.capabilityId,measurementFamily:f,candidateCount:projections.length,requirements:{...r},dimensions:dimensionOrder.map(n=>dims.find(d=>d.dimension===n)!),candidateContexts:contexts,missingComparabilityFacts:[...new Set(missing)],failedComparabilityRequirements:[...new Set(failed)],reasonCodes:status==="COMPARABLE"?["COMPARABLE"]:[...new Set([...missing,...failed])],provenance:{assessment:"BASELINE_MEASUREMENT_COMPARABILITY",projectionStatuses:projections.map(p=>p.status)}});
}
