import { X402BazaarDiscoverySource } from "./external-discovery.js";
import { verifyX402Quote } from "./x402-quote-verification.js";

const args=process.argv.slice(2); const values:string[]=[];
for(let i=0;i<args.length;i++){if(args[i]==="--resource"&&args[i+1]){values.push(args[++i]);continue;} if(/--(all|scan|search)/.test(args[i])||args[i].includes("*")||args[i].includes("?")){console.error("Scanner-like arguments and wildcards are rejected.");process.exitCode=2;break;} console.error(`Unknown argument: ${args[i]}`);process.exitCode=2;break;}
if(!process.exitCode&&(!values.length||values.length>3||new Set(values).size!==values.length)){console.error("Supply one to three distinct exact --resource URLs.");process.exitCode=2;}
const bazaar=process.env.X402_BAZAAR_URL;
if(!process.exitCode&&!bazaar){console.error("Set X402_BAZAAR_URL. Resources are resolved through read-only Bazaar discovery before any probe.");process.exitCode=2;}
if(!process.exitCode){const discovery=await new X402BazaarDiscoverySource({facilitatorUrl:bazaar!,maxPages:Number(process.env.X402_DISCOVERY_MAX_PAGES??1)}).discover(); const selected=values.map(id=>discovery.records.find(r=>r.externalResourceId===id)); console.log(JSON.stringify({selectedResources:values},null,2)); const results:any[]=[];for(const record of selected){if(!record){results.push({resourceId:"unknown",status:"not_found_in_discovery"});continue;}const verified=await verifyX402Quote(record);results.push({discovery:{resourceIdentity:record.externalResourceId,description:record.advertised.description??null,advertisedMethod:record.x402?.invocation?.method??null,schemaAvailability:{input:Boolean(record.advertised.inputSchema),output:Boolean(record.advertised.outputSchema)}},advertisedPayment:record.economics.options.map((o,index)=>({index,x402Version:2,...o})),probe:{constructed:verified.observed.status!=="probe_not_constructible"&&verified.observed.status!=="side_effect_risk",requestCount:verified.requestCount},...verified});} const statuses=results.map(r=>"observed" in r?r.observed.status:r.status);const counted=["payment_required","reachable_without_payment","authentication_required","request_rejected","not_found","method_rejected","rate_limited","server_error","malformed_payment_challenge","network_unreachable","timeout","unsafe_endpoint","probe_not_constructible","side_effect_risk"] as const;const comparisons=results.filter(r=>"comparison" in r).map(r=>r.comparison);console.log(JSON.stringify({results,aggregate:{selected:values.length,foundInDiscovery:selected.filter(Boolean).length,probeConstructible:results.filter(r=>"observed" in r&&!["probe_not_constructible","side_effect_risk"].includes(r.observed.status)).length,networkContacted:results.reduce((n,r)=>n+("requestCount" in r?r.requestCount:0),0),...Object.fromEntries(counted.map(s=>[s,statuses.filter(x=>x===s).length])),advertisedQuoteExactMatches:comparisons.filter(c=>c.matchedAdvertisedOption!==undefined).length,advertisedQuoteMismatches:comparisons.filter(c=>c.discrepancies.length>0).length,unknownComparisons:comparisons.filter(c=>c.paymentProtocolVersion==="unknown").length},safetyCounters:{providerVerificationRequests:results.reduce((n,r)=>n+("requestCount" in r?r.requestCount:0),0),providerPaidRetries:0,paymentSignatureSent:0,paymentClientCalls:0,facilitatorVerify:0,facilitatorSettle:0,providerSuccessfulPaidExecutions:0,mcpToolsCall:0,packageInstallations:0}},null,2));}
