export interface PaymentRequirements { scheme: string; network: string; amount: string; asset: string; payTo: string; maxTimeoutSeconds: number; extra: Record<string, unknown>; }
export interface ResourceInfo { url: string; description?: string; mimeType?: string; serviceName?: string; }
export interface PaymentRequired { x402Version: 2; error?: string; resource: ResourceInfo; accepts: PaymentRequirements[]; extensions: Record<string, unknown>; }
export interface PaymentPayload { x402Version: 2; resource?: ResourceInfo; accepted: PaymentRequirements; payload: Record<string, unknown>; extensions: Record<string, unknown>; }
export interface SettleResponse { success: boolean; transaction: string; network: "eip155:84532"; amount?: string; extensions?: Record<string, unknown>; }
export function encodeX402(value: unknown): string { return Buffer.from(JSON.stringify(value), "utf8").toString("base64"); }
export function decodeX402(value: string): unknown { if (!/^[A-Za-z0-9+/]*={0,2}$/.test(value) || value.length % 4 !== 0) throw new Error("Invalid x402 base64 JSON."); try { const text = Buffer.from(value, "base64").toString("utf8"); if (!text) throw new Error(); return JSON.parse(text); } catch { throw new Error("Invalid x402 base64 JSON."); } }
function isObject(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
export function isPaymentRequirements(value: unknown): value is PaymentRequirements { return isObject(value) && value.scheme === "exact" && typeof value.network === "string" && /^eip155:\d+$/.test(value.network) && typeof value.amount === "string" && /^\d+$/.test(value.amount) && typeof value.asset === "string" && value.asset.length>0 && typeof value.payTo === "string" && value.payTo.length>0 && typeof value.maxTimeoutSeconds === "number" && Number.isFinite(value.maxTimeoutSeconds) && value.maxTimeoutSeconds>=0 && isObject(value.extra); }
export function isPaymentRequired(value: unknown): value is PaymentRequired { const x = value as Record<string, unknown>; return isObject(x) && x.x402Version === 2 && isObject(x.resource) && typeof x.resource.url === "string" && Array.isArray(x.accepts) && x.accepts.length>0 && x.accepts.every(isPaymentRequirements) && isObject(x.extensions); }
export function isPaymentPayload(value: unknown): value is PaymentPayload { const x = value as Record<string, unknown>; return isObject(x) && x.x402Version === 2 && isPaymentRequirements(x.accepted) && isObject(x.payload) && isObject(x.extensions) && (x.resource === undefined || isObject(x.resource)); }
