export interface PaymentRequirements { scheme: "exact"; network: "eip155:84532"; amount: string; asset: string; payTo: string; maxTimeoutSeconds: number; extra: Record<string, unknown>; }
export interface ResourceInfo { url: string; description?: string; mimeType?: string; serviceName?: string; }
export interface PaymentRequired { x402Version: 2; error?: string; resource: ResourceInfo; accepts: PaymentRequirements[]; extensions: Record<string, unknown>; }
export interface PaymentPayload { x402Version: 2; resource?: ResourceInfo; accepted: PaymentRequirements; payload: Record<string, unknown>; extensions: Record<string, unknown>; }
export interface SettleResponse { success: boolean; transaction: string; network: "eip155:84532"; amount?: string; extensions?: Record<string, unknown>; }
export function encodeX402(value: unknown): string { return Buffer.from(JSON.stringify(value), "utf8").toString("base64"); }
export function decodeX402(value: string): unknown { if (!/^[A-Za-z0-9+/]*={0,2}$/.test(value) || value.length % 4 !== 0) throw new Error("Invalid x402 base64 JSON."); try { const text = Buffer.from(value, "base64").toString("utf8"); if (!text) throw new Error(); return JSON.parse(text); } catch { throw new Error("Invalid x402 base64 JSON."); } }
function isObject(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function isRequirements(value: unknown): value is PaymentRequirements { return isObject(value) && value.scheme === "exact" && value.network === "eip155:84532" && typeof value.amount === "string" && /^\d+$/.test(value.amount) && typeof value.asset === "string" && typeof value.payTo === "string" && typeof value.maxTimeoutSeconds === "number" && isObject(value.extra); }
export function isPaymentRequired(value: unknown): value is PaymentRequired { const x = value as Record<string, unknown>; return isObject(x) && x.x402Version === 2 && isObject(x.resource) && typeof x.resource.url === "string" && Array.isArray(x.accepts) && x.accepts.every(isRequirements) && isObject(x.extensions); }
export function isPaymentPayload(value: unknown): value is PaymentPayload { const x = value as Record<string, unknown>; return isObject(x) && x.x402Version === 2 && isRequirements(x.accepted) && isObject(x.payload) && isObject(x.extensions) && (x.resource === undefined || isObject(x.resource)); }
